- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/templates/_helpers.tpl
- charts/victoria-metrics-cluster/templates/clusterrole.yaml
- charts/victoria-metrics-cluster/templates/clusterrolebinding.yaml
- charts/victoria-metrics-cluster/templates/podsecuritypolicy.yaml
- charts/victoria-metrics-cluster/templates/role.yaml
- charts/victoria-metrics-cluster/templates/rolebinding.yaml
- charts/victoria-metrics-cluster/templates/serviceaccount.yaml
- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-cluster/values.yaml
This tries to update and add the necessary things to install the VM chart on clusters with RBAC and PodSecurityPolicy enabled.
I have tested this on K8s v1.14.8 running on Azure AKS with PSP enabled.
I have taken most of the config from the `stable/grafana` chart.
Here is a default install with RBAC and PSP enabled:
```
helm3 upgrade --install vm0 charts/victoria-metrics-cluster
$ kubectl get pods -w
NAME                                                     READY   STATUS    RESTARTS   AGE
vm0-victoria-metrics-cluster-vminsert-6646dc68c5-bqr2m   1/1     Running   0          9m57s
vm0-victoria-metrics-cluster-vminsert-6646dc68c5-jppmn   1/1     Running   0          9m57s
vm0-victoria-metrics-cluster-vmselect-67c5988fd9-jmwqf   1/1     Running   0          9m57s …
```
> Add RBAC and PSP

- charts/victoria-metrics-cluster/templates/clusterrole.yaml
- charts/victoria-metrics-cluster/templates/clusterrolebinding.yaml
- charts/victoria-metrics-cluster/templates/podsecuritypolicy.yaml
- charts/victoria-metrics-cluster/templates/role.yaml
- charts/victoria-metrics-cluster/templates/rolebinding.yaml
- charts/victoria-metrics-cluster/templates/serviceaccount.yaml
- charts/victoria-metrics-cluster/templates/vminsert-ingress.yaml
- charts/victoria-metrics-cluster/templates/vmselect-ingress.yaml
- charts/victoria-metrics-single/templates/clusterrole.yaml
- charts/victoria-metrics-single/templates/clusterrolebinding.yaml
- charts/victoria-metrics-single/templates/podsecuritypolicy.yaml
- charts/victoria-metrics-single/templates/role.yaml
- charts/victoria-metrics-single/templates/rolebinding.yaml
- charts/victoria-metrics-single/templates/serviceaccount.yaml
This is related to #6, using extraLabels will give the `error converting YAML to JSON` error because the first label has an extra indent.
> fix extraLabels indentation

- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-cluster/templates/vminsert-service-monitor.yaml
- charts/victoria-metrics-cluster/templates/vmselect-service-monitor.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-service-monitor.yaml
It is often common practice to place the ServiceMonitor manifest in another namespace, e.g., `monitoring`. Thus, it would be nice to have the ability to optionally set the target namespace for the ServiceMonitor.
> Making it possible to set namespace on ServiceMonitor manifest

- charts/victoria-metrics-single/README.md
I noticed this parameter was undocumented but still usable, so I added it to the README
> Add storageClass parameter in victoria-metrics-single to README

- charts/victoria-metrics-single/templates/server-deployment.yaml
When a pvc is attached, the deployment won't be able to create a new pod
after an upgrade until the first pod dies/is deleted. Changing the deployment
strategy to 'Recreate' allows upgrades to proceed as expected.
> Fix server deployment upgrade requiring a manual pod delete

- charts/victoria-metrics-single/templates/server-service-headless.yaml
- charts/victoria-metrics-single/templates/server-service.yaml
- charts/victoria-metrics-single/templates/server-statefulset.yaml
Current single chart is missing namespace for statefulset, and service objects.
Maybe other charts here are also missing it, but haven't had the time to inspect.
> Add missing namespace to single chart

- charts/victoria-metrics-agent/templates/clusterrole.yaml
GCE k8s cluster a have got error:
```
1s, error="unexpected status code returned when scraping \"https://10.138.0.121:10250/metrics\": 403; expecting 200; response body: \"Forbidden (user=system:serviceaccount:devops:vmagent-gcp-stg-victoria-metrics-agent, verb=get, resource=nodes, subresource=metrics)\""
```
add one more resource to cluster role
> Fix kubelest cadvisor forbidden scrape problem

- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-single/templates/server-statefulset.yaml
This PR is fixing yaml linter error : `error    duplication of key "affinity" in mapping  (key-duplicates)`
> fix: remove duplicated key affinity in sts

- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-agent/templates/pdb.yaml
- charts/victoria-metrics-agent/values.yaml
- charts/victoria-metrics-alert/Chart.yaml
- charts/victoria-metrics-alert/templates/server-pdb.yaml
- charts/victoria-metrics-alert/values.yaml
- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/templates/vminsert-pdb.yaml
- charts/victoria-metrics-cluster/templates/vmselect-pdb.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-pdb.yaml
- charts/victoria-metrics-cluster/values.yaml
Allow enabling PodDisruptionBudget for:
- VM cluster (vmselect, vmstorage and vminsert)
- vmagent
- vmalert
> PodDisruptionBudget for VM, vmagent and vmalert

- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-cluster/values.yaml
This change adds optional pod labels to vmselect, vminsert and vmstorage.
I bumped the version in case of issues.
> Add optional pod labels

- charts/victoria-metrics-agent/templates/deployment.yaml
It fixes partially this issue :
https://github.com/VictoriaMetrics/helm-charts/issues/64
> Use emptyDir volume to store the vmagent buffer

- charts/victoria-metrics-agent/templates/clusterrole.yaml
- charts/victoria-metrics-alert/templates/role.yaml
- charts/victoria-metrics-alert/templates/rolebinding.yaml
- charts/victoria-metrics-cluster/templates/role.yaml
- charts/victoria-metrics-cluster/templates/rolebinding.yaml
- charts/victoria-metrics-single/templates/role.yaml
- charts/victoria-metrics-single/templates/rolebinding.yaml
`rbac.authorization.k8s.io/v1beta1` was deprecated in k8s 1.17, and will no longer be served in v1.22.
In the VictoriaMetrics' charts we can see a mix of both `v1beta1` and `v1`. I think it's time to promote everything to `v1`.
> Promote rbac.authorization.k8s.io to v1

- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-agent/templates/deployment.yaml
- charts/victoria-metrics-agent/values.yaml
Instead of just host mounts. This allows you to mount, for example, CA
certificates for self-signed TLS scrape targets
```
$ cat test.yaml
extraVolumes:
- name: example
configMap:
name: example
extraVolumeMounts:
- name: example
mountPath: /example
$ helm template . -f test.yaml --show-only templates/deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
name: RELEASE-NAME-victoria-metrics-agent
namespace: default
labels:
helm.sh/chart: victoria-metrics-agent-0.6.1
app.kubernetes.io/name: victoria-metrics-agent
app.kubernetes.io/instance: RELEASE-NAME
app.kubernetes.io/version: "v1.44.0"
app.kubernetes.io/managed-by: Helm
spec:
replicas: 1
selector:
matchLabels:
app.kubernetes.io/name: victoria-metrics-agent
app.kubernetes.io/instance: RELEASE-NAME
template:
metadata:
labels: …
```
> [agent] Support Arbitrary Volumes

- charts/victoria-metrics-cluster/README.md
Adjusted formatting of README.md for victoria-metrics-cluster.
Highlights:
* added trailing "|" where needed (otherwise, some software like Typora fails to render the table);
* fixed markdown issues highlighted by markdownlint;
* fixed typos.
> victoria-metrics-cluster: formatting fixes for README.md

- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-single/templates/server-statefulset.yaml
**Description**
Starting from v1.45.0, VM allows to have retention periods smaller than one month (https://github.com/VictoriaMetrics/VictoriaMetrics/issues/173).
The issue is that the current template fails to render non-numerical values like `5d`, `1w` - they produce  `--retentionPeriod=0`
**Bugfix**
The proposed bugfix changes the respective templates to let them treat `.Values.vmstorage.retentionPeriod` and `.Values.server.retentionPeriod` as strings instead of numbers. So, values in any format become possible.
> Bugfix for retention period smaller than one month (vmstorage/single)

- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-cluster/templates/_helpers.tpl
- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
fixes issue https://github.com/VictoriaMetrics/helm-charts/issues/89
It possible to use --selectNode flag only with statefulset version of vmselect.
> adds selectNode param for vmselect,

- charts/victoria-metrics-single/README.md
- charts/victoria-metrics-single/templates/server-deployment.yaml
- charts/victoria-metrics-single/templates/server-statefulset.yaml
- charts/victoria-metrics-single/values.yaml
Did the same as https://github.com/VictoriaMetrics/helm-charts/pull/108
@f41gh7 
What do you think, would it be better to add custom labels to `{{- define "victoria-metrics.server.labels" -}}`?
https://github.com/VictoriaMetrics/helm-charts/issues/109
> #109 custom labels for victoria-metrics-single

- charts/victoria-metrics-alert/Chart.yaml
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/templates/server-deployment.yaml
When deploying the vmalert chart, templating will fail if neither a config nor an existing configmap are provided in the values. There is another way to provide rules to vmalert though, through the `rule` argument. This PR allows a deployment with no config or configmap as long as an additional rule parameter is provided.
> [vmalert] allow empty config if rule file specified

- charts/victoria-metrics-cluster/templates/role.yaml
In victoria-metrics-cluster version 0.8.17, setting `rbac.pspEnabled=false` produces an invalid Role - the `rules` key is listed twice.
`helm template vm vm/victoria-metrics-cluster --version 0.8.17 --set rbac.pspEnabled=false | grep -A 11 -F 'Source: victoria-metrics-cluster/templates/role.yaml'`
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
name: vm-victoria-metrics-cluster
namespace: default
labels:
helm.sh/chart: victoria-metrics-cluster-0.8.17
app.kubernetes.io/managed-by: Helm
rules:
rules: []
---
```
Compare `victoria-metrics-cluster/templates/role.yaml` with `victoria-metrics-cluster/templates/clusterole.yaml`; latter works.
Move the rules key into conditional block.
> Produce valid Role rules when rbac.pspEnabled=false

- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/values.yaml
we have had an issue with an 'initialDelaySeconds' on readiness probe - and predefined 5 seconds wasn't enough. So, we need this change to increase the value for this option. Kindly hope you'll find it useful ;) thanks
> Added go_template for readiness & liveness probes (initialDelaySeconds)

- charts/victoria-metrics-k8s-stack/hack/sync_grafana_dashboards.py
- charts/victoria-metrics-k8s-stack/hack/sync_rules.py
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-resources-cluster.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-resources-pod.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-resources-workload.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-resources-workloads-namespace.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/node-cluster-rsrc-use.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/node-rsrc-use.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/nodes.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/victoriametrics.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/vmagent.yaml
- charts/victoria-metrics-k8s-stack/templates/rules/general.rules.yaml
- charts/victoria-metrics-k8s-stack/templates/rules/kubernetes-resources.yaml
- charts/victoria-metrics-k8s-stack/templates/rules/node-exporter.rules.yaml
- charts/victoria-metrics-k8s-stack/templates/rules/serviceHealth.yaml
- charts/victoria-metrics-k8s-stack/templates/rules/vmagent.yaml
- charts/victoria-metrics-k8s-stack/templates/rules/vmsingle.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/monzo-template.yaml
* VM dashboards now also pulled with `sync_dashboards` script for unified approach
* VM rules for VictoriaMetrics updated to point to proper grafana ingress #141 
* Updated all rules and dashboards from kube-mixin
> Update dashboards, rules and dashboard url for VictoriaMetrics rules

- charts/victoria-metrics-alert/Chart.yaml
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/templates/alertmanager-configmap.yaml
- charts/victoria-metrics-alert/values.yaml
Added the ability to fill in templates for the alertmanager.
Based on https://github.com/prometheus-community/helm-charts/tree/main/charts/alertmanager
Signed-off-by: Igor Churmeev <ichurmeev@makezbs.com>
> Add alertmanager templates ability

- charts/victoria-metrics-alert/templates/alertmanager-configmap.yaml
Templates should be stored in a separate files outside alertmanager.yaml
> moved templates outside alertmanager.yaml

- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-hpa.yaml
- charts/victoria-metrics-cluster/values.yaml
Configuration to allow the vmselect component to be scaled based on its CPU Utilization. 
We are already using this in our production vm-clusters.
> Add HPA Support to vmselect component

- charts/victoria-metrics-single/templates/server-deployment.yaml
- charts/victoria-metrics-single/templates/server-statefulset.yaml
- charts/victoria-metrics-single/values.yaml
Startup of application is often more demanding on cpu/memory then rest of the runtime. Sometimes it is hard to tune readiness/liveness probes so that they allow application to start but are responsive enough for issues during normal operation. Startup probe can save the day here.
VictoriaMetrics is no difference. Full disk for example can cause compactification to be halted. After volume is enlarged startup of Victoria takes longer since it needs to catch up in maintenance backlog.
Thus I propose adding support for startup probes into official Helm chart.
> Add startup probe support

- charts/victoria-metrics-k8s-stack/Chart.lock
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
- charts/victoria-metrics-k8s-stack/templates/servicemonitors/coredns.yaml
- charts/victoria-metrics-k8s-stack/templates/servicemonitors/grafana.yaml
- charts/victoria-metrics-k8s-stack/templates/servicemonitors/kube-controller-manager.yaml
- charts/victoria-metrics-k8s-stack/templates/servicemonitors/kube-etcd.yaml
- charts/victoria-metrics-k8s-stack/templates/servicemonitors/kube-proxy.yaml
- charts/victoria-metrics-k8s-stack/templates/servicemonitors/kube-scheduler.yaml
- charts/victoria-metrics-k8s-stack/templates/servicemonitors/kube-state-metrics.yaml
- charts/victoria-metrics-k8s-stack/templates/servicemonitors/nodeexporter.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/custom-templates.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
1. allow set custom alertmanager templates as in prometheus-operator
```
alertmanager:
templateFiles:
template_1.tmpl: |-
{{ define "hello" -}}
hello, Victoria!
{{- end }}
template_2.tmpl:  |-
{{ define "bye" -}}
arrivederci!
{{- end }}
```
2. We use it with argocd, and it uses label app.kubernetes.io/instance to define release and always overrides it.
And if set releaseName in argocd, then VMServiceScrape select incorrect labels.
I've set the "argocdReleaseOverride" value and can manage with it.
> Extra alertmanagerTemplates and argocd releaseName issue

- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/hack/sync_grafana_dashboards.py
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/vmalert.yaml
- charts/victoria-metrics-k8s-stack/templates/rules/kube-apiserver-availability.rules.yaml
- charts/victoria-metrics-k8s-stack/templates/rules/kubernetes-system-kubelet.yaml
- charts/victoria-metrics-k8s-stack/templates/servicemonitors/nodeexporter.yaml
in #193 `argocdReleaseOverride` was introduced
but for nodeexporter service scrape we initally were overriding `release` while argo actually doesn't touch release label and only overrides `app.kubernetes.io/instance`
also added vmalert dashboard, thanks @hagen1778
> Nodexporter servicescrape argo fix

- charts/victoria-metrics-agent/values.yaml
I noticed that the example config was referring to a pod label in the service configs, hence all the service metrics were dropped.
> Fix scrape config for kubernetes-service-endpoints

- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/hack/sync_grafana_dashboards.py
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/alertmanager-overview.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/apiserver.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/cluster-total.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/controller-manager.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/etcd.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-resources-cluster.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-resources-namespace.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-resources-node.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-resources-pod.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-resources-workload.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-resources-workloads-namespace.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/kubelet.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/namespace-by-pod.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/namespace-by-workload.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/node-cluster-rsrc-use.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/node-rsrc-use.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/nodes.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/persistentvolumesusage.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/pod-total.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/proxy.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/scheduler.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/victoriametrics-cluster.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/victoriametrics.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/vmagent.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/vmalert.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/workload-total.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
Drill-down links doesn't work properly in grafana 8
https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/659
so i added ugly fix in sync_grafana script
also updated VM components to 1.66.2
> Fix drilldown grafana 8

- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/values.yaml
This Pr will allow to use `topologySpreadConstraints` to spread pods between zones in case you have a cluster per zone architecture.
> add topologySpreadConstraints to select deployment to make it possible to spread them between az

- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-single/Chart.yaml
- charts/victoria-metrics-single/templates/server-deployment.yaml
- charts/victoria-metrics-single/templates/server-statefulset.yaml
This MR fixes a bug when it's not possible to specify already existing service account for single/cluster VM versions
> Specify custom service account

- charts/victoria-metrics-single/values.yaml
Identical to #146 but for victoria-metrics-single chart.
> Fix scrape config for kubernetes-service-enpoints (victoria-metrics-single)

- charts/victoria-metrics-single/templates/clusterrole.yaml
Fix victoria-metrics-single ClusteRole to include missing `networking.k8s.io` causing permission error when using `role: ingress` in `kubernetes_sd_configs`.
In victoria-metrics-agent chart the same fix is applied at [this commit](https://github.com/VictoriaMetrics/helm-charts/commit/5f41ebda18caab18d6a88ad43502da91411d0852).
> [victoria-metrics-single] Fix ClusterRole to include networking.k8s.io

- charts/victoria-metrics-agent/README.md
- charts/victoria-metrics-agent/templates/pvc.yaml
- charts/victoria-metrics-agent/templates/statefulset.yaml
- charts/victoria-metrics-agent/values.yaml
- charts/victoria-metrics-single/README.md
- charts/victoria-metrics-single/templates/server-pvc.yaml
- charts/victoria-metrics-single/templates/server-statefulset.yaml
- charts/victoria-metrics-single/values.yaml
This is important when Persistent Volumes are provisioned in advance.
This is similar to [Prometheus chart `prometheus-community/helm-charts`][1].
[1]: https://github.com/prometheus-community/helm-charts/blob/prometheus-14.11.0/charts/prometheus/values.yaml#L919
> Add 'persistence.matchLabels' option to vmsingle and vmagent

- charts/victoria-metrics-alert/templates/server-deployment.yaml
- charts/victoria-metrics-alert/values.yaml
This change will help when ensuring new vmalert pods can be spun up within a deployment
and be running  their rules before the old pods spin down.
> Add minReadySeconds and strategy fields

- charts/victoria-metrics-k8s-stack/templates/grafana/datasource.yaml
The datasource.yaml-boilerplate needs to be present if *any* datasource is enabled; including `.Values.grafana.additionalDataSources`.
Before this change the chart would fail if both `.Values.vmsingle.enabled` & `.Values.vmcluster.enabled` was set to `false`, but `.Values.grafana.additionalDataSources` was containing dashboard configuration.
I've only tested this with the above mentioned circumstances.
> Include datasource.yaml for any datasource

- charts/victoria-metrics-k8s-stack/templates/grafana/datasource.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
We are using a polling interval of 1m (for snmp-exporter) and would like to change the default interval on the provisioned VM datasources in Grafana (see [docs](https://grafana.com/docs/grafana/latest/administration/provisioning/#json-data)). With this PR, we can change it as follows:
```yaml
grafana:
sidecar:
datasources:
jsonData:
timeInterval: "1m"
```
> Allow setting jsonData for Grafana datasource(s)

- charts/victoria-metrics-operator/templates/deployment.yaml
Kubernetes's Pod specification requires environment variable values to be strings. I run into an issue trying to set environment variables to "false" or "true" as those get converted to boolean.
The example bellow results in a templating error.
```
env:
- name: TEST123
value: "false"
```
```
v1.EnvVar.Value: ReadString: expects " or n, but found f, error found in #10 byte of ...|,"value":false},{"na|..., bigger context ...|nd":["manager"],"env":[{"name":"TEST123","value":false},{"name":"WATCH_NAMESPACE","value":""},{"name|...
```
> quote var value to avoid string-to-bool conversion

- charts/victoria-metrics-agent/templates/service-monitor.yaml
- charts/victoria-metrics-agent/values.yaml
- charts/victoria-metrics-alert/templates/service-monitor.yaml
- charts/victoria-metrics-alert/values.yaml
- charts/victoria-metrics-auth/templates/service-monitor.yaml
- charts/victoria-metrics-auth/values.yaml
- charts/victoria-metrics-cluster/templates/vminsert-service-monitor.yaml
- charts/victoria-metrics-cluster/templates/vmselect-service-monitor.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-service-monitor.yaml
- charts/victoria-metrics-cluster/values.yaml
- charts/victoria-metrics-single/templates/server-service-monitor.yaml
- charts/victoria-metrics-single/values.yaml
Adding on all existing VictoriaMetrics charts the possibility to tune :
-  [ServiceMonitorSpec](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#servicemonitorspec).[Endpoint](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#endpoint).scheme
- [ServiceMonitorSpec](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#servicemonitorspec).[Endpoint](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#endpoint).[TLSConfig](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#tlsconfig)
Making this PR after [discussion](https://victoriametrics.slack.com/archives/CGZF1H6L9/p1643646902896069) on #general …
> add scheme + tlsConfig endpoint option for servicemonitor

- charts/victoria-metrics-single/values.yaml
Actually, the way helm chart victoriametrics-single is templatized does not allow me to use `httpGet` instead of `TcpSocket`. Which is mandatory if I want to avoid error logs like that force us to remove the `TooManyLogs` alert :vomiting_face: 
```
{"ts":"2022-02-01T17:33:09.490Z","level":"error","caller":"net/http/server.go:3158","msg":"http: TLS handshake error from X.X.X.X:58276: EOF"}
```
Those logs are triggered with the `tcpSocket` livenessProbe
-----------------------
Using actual victoriametrics-single helm chart, if I try to tune the helm chart to use `httpGet` using follow values : 
```
server:
livenessProbe:
httpGet:
scheme: HTTPS
path: /health
port: 8428
```
Because of default livenessProbe values, my livenessprobe deployment will look like this :
```
livenessProbe: …
```
> fix livenessProbe for TLS configured VM-single 

- charts/victoria-metrics-k8s-stack/templates/servicemonitors/cadvisor.yaml
- charts/victoria-metrics-k8s-stack/templates/servicemonitors/kubelet-probes.yaml
`.Values.kubelet.cadvisor` / `.Values.kubelet.probes` wrong way around.
Noticed this when reading around how to use the helm chart.  Pretty sure this is just a copy/paste error.
> Mixed helm chart values

- charts/victoria-metrics-alert/templates/alertmanager-deployment.yaml
I am using [charts/victoria-metrics-alert](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts) to configure the alertmanager, but I found the following errors in the alertmanager pod logs:
```
level=info ts=2022-02-09T08:56:36.032Z caller=silence.go:379 component=silences msg="Running maintenance failed" err="open /alertmanager/silences.7153164ab75d6846: permission denied"
level=error ts=2022-02-09T08:56:36.032Z caller=nflog.go:365 component=nflog msg="Running maintenance failed" err="open /alertmanager/nflog.5d365deceefa53d9: permission denied"
```
Inside the pod, it also shows the permission denied error
```
/data $ touch example
touch: example: Permission denied
/data $ id
uid=65534(nobody) gid=65534(nogroup)
```
even if I have defined the fsGroup in the values.yaml like …
> add securityContext in alertmanager-deployment.yaml

- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-agent/README.md
- charts/victoria-metrics-agent/templates/deployment.yaml
- charts/victoria-metrics-agent/templates/statefulset.yaml
- charts/victoria-metrics-agent/values.yaml
On congested clusters the vmagent pod can be preempted in favor of higher priority pods, which might not be desirable in all cases.
This PR adds the possibility to configure `priorityClassName` for the `Deployment` and `StatefulSet` pods (by default it's unset).
> vmagent: add possibility to configure pod priority class

- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-agent/README.md
- charts/victoria-metrics-agent/templates/service-monitor.yaml
- charts/victoria-metrics-agent/values.yaml
- charts/victoria-metrics-alert/Chart.yaml
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/templates/service-monitor.yaml
- charts/victoria-metrics-alert/values.yaml
- charts/victoria-metrics-auth/Chart.yaml
- charts/victoria-metrics-auth/README.md
- charts/victoria-metrics-auth/templates/service-monitor.yaml
- charts/victoria-metrics-auth/values.yaml
- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-cluster/templates/vminsert-service-monitor.yaml
- charts/victoria-metrics-cluster/templates/vmselect-service-monitor.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-service-monitor.yaml
- charts/victoria-metrics-cluster/values.yaml
- charts/victoria-metrics-gateway/Chart.yaml
- charts/victoria-metrics-gateway/README.md
- charts/victoria-metrics-gateway/templates/service-monitor.yaml
- charts/victoria-metrics-gateway/values.yaml
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-single/Chart.yaml
- charts/victoria-metrics-single/README.md
- charts/victoria-metrics-single/templates/server-service-monitor.yaml
- charts/victoria-metrics-single/values.yaml
Hi,
This is a small change to allow defining relabelings for serviceMonitors. Looks like nobody run `helm-docs` for a while and it updated a few readme files not related to this PR.
Thanks,
Arcadie
> Add optional relabelings for serviceMonitors

- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-agent/README.md
- charts/victoria-metrics-agent/templates/service.yaml
- charts/victoria-metrics-agent/values.yaml
- charts/victoria-metrics-alert/Chart.yaml
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/templates/server-service.yaml
- charts/victoria-metrics-alert/values.yaml
- charts/victoria-metrics-auth/Chart.yaml
- charts/victoria-metrics-auth/README.md
- charts/victoria-metrics-auth/templates/service.yaml
- charts/victoria-metrics-auth/values.yaml
- charts/victoria-metrics-gateway/Chart.yaml
- charts/victoria-metrics-gateway/README.md
- charts/victoria-metrics-gateway/templates/service.yaml
- charts/victoria-metrics-gateway/values.yaml
- charts/victoria-metrics-single/Chart.yaml
- charts/victoria-metrics-single/README.md
- charts/victoria-metrics-single/templates/server-service.yaml
- charts/victoria-metrics-single/values.yaml
Hi, this PR is exposing nodePort config where it might be useful (related to #98):
- victoria-metrics-agent
- victoria-metrics-alert
- victoria-metrics-auth
- victoria-metrics-gateway
- victoria-metrics-single
> expose "nodePort" in service configuration

- charts/victoria-metrics-cluster/templates/vminsert-service.yaml
- charts/victoria-metrics-cluster/values.yaml
with this change, if service type `LoadBalancer` and `extraArgs.opentsdbListenAddr` specified for VMinsert, by default UDP port will not be created in service spec. Because out of the box LoadBalancer service type doesn't support TCP and UDP in one service. 
However if needed, `udp: true` may be specified. this is to cover cases when feature gate `MixedProtocolLBService` enabled
addresses #319
> [cluster] disable udp port for service type LoadBalancer by default

- charts/victoria-metrics-agent/values.yaml
fix: victoria-metrics-agent  `statefulset.clusterMode` values misspell, should be **clusterMode**.  @valyala
> fix: agent statefulset clusterMode values misspell

- charts/victoria-metrics-agent/values.yaml
Replaces `role: endpoints` with `role: endpointslices` for kubernetes service discovery
It should fix error `the number of targets for "role: endpoints" exceeds 1000 and will be truncated in the next k8s releases`
> charts/victoria-metrics-agent: replaces endpoints role

- charts/victoria-metrics-agent/templates/clusterrole.yaml
Need to add endpointslices to list of allowed resources to ClusterRole definition in victoria-metrics-agent chart.
> Add endpointslices permissions to ClusterRole manifest

- charts/victoria-metrics-agent/templates/clusterrole.yaml
Endpointslices are not in base api groups. They are from discovery.k8s.io api group.
Need to be defined explicitly in clusterrole manifest.
> Fix victoria-metrics-agent clusterrole

- charts/victoria-metrics-k8s-stack/crds/crd.yaml
- charts/victoria-metrics-operator/templates/crd.yaml
- charts/victoria-metrics-operator/templates/crd_legacy.yaml
Hi! 
I found a typo in the CRD manifests.
There was duplicated "markdown" and no "HTML" option.
Link to the official docs: https://prometheus.io/docs/alerting/latest/configuration/#telegram_config
> Fix typo in telegram_configs.parse_mode

- charts/victoria-metrics-operator/templates/webhook.yaml
Hello!
There is a one typo in vm-operator webhook manifest template
Fixed it
> Fix typo in vmrule webhook

- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
- When you disabled vminsert,  empty manifest shown up
```
---
volumes:
```
- fixed PR https://github.com/VictoriaMetrics/helm-charts/pull/308
> Fix victoria-metrics-cluster  wrong end of template

- charts/victoria-metrics-single/templates/server-statefulset.yaml
When deploying with a StatefulSet, podSecurityContext was not exposed as it was with the Deployment template, making it impossible to use the Helm chart with our secured cluster.
This exposes it.
> Expose podSecurityContext also for StatefulSet

- charts/victoria-metrics-single/values.yaml
victoria-metrics-single.
Pardon me if I'm missing something, but it looks like the volume size here does not correspond to memory itself, rather a storage for the metrics persisting.
> Correct comment on persistentVolume size: option

- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/uninstall_hook.yaml
This fixes a bug whereby running clusters with tainted nodes (e.g. Spot nodes in AKS are tainted out the box) means you cannot run the cleanup helm hook and you cannot remove the helm release from your cluster without first removing the finalizer
> Schedule operator cleanup hook onto operator nodes/affinity/tolerations

- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-service-headless.yaml
- charts/victoria-metrics-cluster/templates/vmselect-service.yaml
- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
vmselect already supported multi-level cluster setup by setting clusternativeListenAddr.
> Add clusternativeListenAddr port support in vmselect chart

- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/templates/alertmanager-deployment.yaml
- charts/victoria-metrics-alert/values.yaml
This adds an additional support to the existing `alertmanager.baseURL` that allows the customization of the prefix `alertmanager.baseURLPrefix`
> Add AlertManager External URL Prefix

- charts/victoria-metrics-gateway/README.md
- charts/victoria-metrics-gateway/README.md.gotmpl
Fix wrong grep pattern in README.md for vmgateway
**Get the pods lists by running this commands** section contain:
```console
kubectl get pods -A | grep 'vminsert\|vmselect\|vmstorage'
```
when it should be:
```console
kubectl get pods -A | grep 'vmgateway'
```
> charts/victoria-metrics-gateway/README.md: fix wrong command

- charts/victoria-metrics-k8s-stack/hack/sync_rules.py
- charts/victoria-metrics-k8s-stack/templates/rules/kube-apiserver-burnrate.rules.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/_rules.tpl
- charts/victoria-metrics-k8s-stack/values.yaml
Title says all :) This PR allows it to disable the generation of the kinda resource intensive kube-apiserver-burnrate rules.
> victoria-metrics-k8s-stack: add conditions for kube-apiserver-burnrate.rules

- charts/victoria-metrics-agent/templates/clusterrole.yaml
- charts/victoria-metrics-agent/templates/podsecuritypolicy.yaml
- charts/victoria-metrics-agent/values.yaml
- charts/victoria-metrics-alert/templates/podsecuritypolicy.yaml
- charts/victoria-metrics-alert/templates/role.yaml
- charts/victoria-metrics-alert/values.yaml
- charts/victoria-metrics-auth/templates/podsecuritypolicy.yaml
- charts/victoria-metrics-auth/values.yaml
- charts/victoria-metrics-cluster/templates/clusterrole.yaml
- charts/victoria-metrics-cluster/templates/podsecuritypolicy.yaml
- charts/victoria-metrics-cluster/templates/role.yaml
- charts/victoria-metrics-cluster/values.yaml
- charts/victoria-metrics-operator/templates/psp.yaml
- charts/victoria-metrics-operator/values.yaml
- charts/victoria-metrics-single/templates/clusterrole.yaml
- charts/victoria-metrics-single/templates/podsecuritypolicy.yaml
- charts/victoria-metrics-single/templates/role.yaml
- charts/victoria-metrics-single/values.yaml
This change will make Helm check for the presence of the `policy/v1beta1` API, before it deploys `podSecurityPolicy` resources, which are no longer supported with Kubernetes 1.25.
Fixes #390.
> deploy `podSecurityPolicy` resources only if Kubernetes (<1.25) supports the resource

- charts/victoria-metrics-agent/README.md
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-auth/README.md
- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-gateway/README.md
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-single/Chart.yaml
- charts/victoria-metrics-single/README.md
- charts/victoria-metrics-single/templates/clusterrole.yaml
VictoriaMetrics Single Server is unable to discover Kubernetes Service Endpoints with its current Cluster role rules. This PR addresses this problem by adding the necessary rule to the Cluster role.
> fix: add missing clusterrole rule for serviceendpoint discovery

- charts/victoria-metrics-k8s-stack/hack/sync_grafana_dashboards.py
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/victoriametrics-cluster.yaml
Due typo in the script vm-cluster dashboard was replaced with the vm-single version.
> [victoria-metrics-k8s-stack]: Fix vm-cluster dashboard

- charts/victoria-metrics-k8s-stack/values.yaml
Remove external label 'cluster' as it breaks cassandra jobs as it also has this label in its metrics. Anyway this label`s default value 'cluster-name' is useless and should be set only if needed.
> removed external label

- charts/victoria-metrics-single/templates/_helpers.tpl
- charts/victoria-metrics-single/templates/server-deployment.yaml
- charts/victoria-metrics-single/templates/server-statefulset.yaml
- charts/victoria-metrics-single/values.yaml
* Add extraVolumeMounts to the vmbackupmanager container.
It helps to mount s3/gcp config for the vmbackup utils.
* Fix duplicate container name.
> Add extraVolumeMounts to the vmbackupmanager

- charts/victoria-metrics-anomaly/templates/configmap.yaml
- charts/victoria-metrics-anomaly/values.yaml
Makes `monitoring` top-level config option as required for `vmanomaly`
Use `enabled` for consistency with another parameters.
> vmanomaly: fix config formatting, make naming consistent

- .github/labeler.yaml
- charts/victoria-metrics-anomaly/templates/deployment.yaml
Currently, pod won't be recreated after CM change, so it will require either waiting until next restart or manual restart.
This PR adds annotation which will be changed after CM change, this will force pod recreation.
> vmanomaly: add annotation for pods to trigger recreating pod after config change

- charts/victoria-metrics-cluster/templates/vmstorage-pdb.yaml
While switching the `vmstorage.enabled` flag to false, the **Service** and **StatefulSet** are removed from the rendered manifest but not the **PDB**. Looking at all the templates, it looks like this `if` statement is missing from the PDB template.
> PDB is still created when vmstorage.enabled is set to false

- .github/workflows/run-testing.yaml
Downgrade version to match versions supported by k3s.
Current versions were taken to be latest k8s versions, but k3s doesn't support these versions yet.
> ci: fix k3s versions

- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/ingress.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmagent.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmalert/vmalert.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmcluster.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmsingle.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
- hack/helm/victoria-metrics-k8s-stack.yaml
ArgoCD checks were not working due to https://github.com/argoproj/argo-cd/issues/7291
This PR makes checks on per-API basis instead of resources ones.
Fixes  #435
> k8s-stack: fix ingress API check to be compatible with ArgoCD

- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
- charts/victoria-metrics-cluster/templates/vminsert-service.yaml
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-service.yaml
- charts/victoria-metrics-cluster/values.yaml
The extraContainer support was partly broken, partly missing. With these changes it is possible to inject a sidecar container into vminsert & vmselect PODs. Such extra container can terminate incoming traffic, perform authentication and proxy traffic to the "real" container.
> Fix sidecar support

- charts/victoria-metrics-agent/templates/clusterrole.yaml
- charts/victoria-metrics-agent/templates/clusterrolebinding.yaml
- charts/victoria-metrics-agent/templates/podsecuritypolicy.yaml
- charts/victoria-metrics-alert/templates/podsecuritypolicy.yaml
- charts/victoria-metrics-auth/templates/podsecuritypolicy.yaml
- charts/victoria-metrics-cluster/templates/clusterrole.yaml
- charts/victoria-metrics-cluster/templates/clusterrolebinding.yaml
- charts/victoria-metrics-cluster/templates/podsecuritypolicy.yaml
- charts/victoria-metrics-single/templates/clusterrole.yaml
- charts/victoria-metrics-single/templates/clusterrolebinding.yaml
- charts/victoria-metrics-single/templates/podsecuritypolicy.yaml
Fixes [#354](https://github.com/VictoriaMetrics/helm-charts/issues/354) 
Cluster-scoped resources need no namespace field. Some tools, like terraform-kustomization-provider, will throw validation errors if these fields exist
> Remove namespaces from cluster-scoped objects

- charts/victoria-metrics-anomaly/templates/configmap.yaml
- charts/victoria-metrics-anomaly/templates/deployment.yaml
- `unset` was removing value from dict, so that `if` in CM was not evaluating to `true`
- added port definition for pod to make it easier to configure pod scraping
> vmanomaly: fix config for pull-based monitoring

- charts/victoria-metrics-cluster/templates/vminsert-service.yaml
- charts/victoria-metrics-cluster/templates/vmselect-service-headless.yaml
- charts/victoria-metrics-cluster/templates/vmselect-service.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-service.yaml
- charts/victoria-metrics-cluster/values-sidecar.yaml
- charts/victoria-metrics-cluster/values.yaml
When adding a sidecar for tls&auth in the vminsert/vmselect pods, the corresponding service needs 2 ports. One for external traffic and one for metrics.
> Fix service ports

- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
When vmcluster.spec.vmselect.extraArgs.http.pathPrefix and vmcluster.spec.vminsert.extraArgs.http.pathPrefix is not defined(as it is by default) address becomes invalid as it adds extra slash after port number.  
i.e: http://vmselect-k8s-stack.default.svc:8481//select/0/prometheus
> fix vmReadEndpoint and vmWriteEndpoint

- charts/victoria-metrics-agent/README.md
- charts/victoria-metrics-agent/templates/clusterrole.yaml
- charts/victoria-metrics-agent/templates/clusterrolebinding.yaml
- charts/victoria-metrics-agent/values.yaml
For a certain use case, I need to run victoria-metrics-agent in a single namespace w/o clusterroles/clusterrolebinding.
The chart as is does give me the option of installing without the ClusterRole/ClusterRoleBinding via the .Values.rbac.create. It would be useful for me if I could tell it to created a namespaced RBAC.
I am aware this is different than some of the other helm charts here. For example, I do see that the `victoria-metrics-alert` chart used the same flag and behaves as following (if .Values.rbac.create is true):
- Create the Role/RoleBinding
- If not namespaced, also create the ClusterRole/ClusterRoleBinding
I went with the approach in this PR as it is the least code changes and the most maintainable (as it doesn't add an additional two files/CRs).
> Add namespaced flag for vmagent

- charts/victoria-metrics-alert/values.yaml
Bumped alertmanager version to v0.25.0 because the default version is more than obsolete (v0.20.0 from 2019).
> [victoria-metrics-alert] Bumped default alertmanager version to v0.25.0

- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-cluster/values.yaml
**Description of the change**
This PR adds the configuration of labels to PVC.
**Benefits**
We use this chart to provision temporary database and then remove it in CI/CD. This labels let us to delete PVC after uninstall chart.
> [charts/victoria-metrics-cluster] add PVC labels

- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/servicescrape.yaml
When deployed via argocd servicescrape is selecting wrong labels
> fix label selector for argocd

- charts/victoria-metrics-operator/templates/deployment.yaml
I found some bugs when I used `extraArgs` of operators. The chart resolves `extraArgs` as shorthand and `operator` via `pflag` so that `--` and `-` have different meanings.
> [victoria-metrics-operator]:fix extraArgs options

- .github/workflows/run-testing.yaml
- charts/victoria-metrics-agent/templates/clusterrole.yaml
- charts/victoria-metrics-agent/templates/podsecuritypolicy.yaml
- charts/victoria-metrics-alert/templates/podsecuritypolicy.yaml
- charts/victoria-metrics-alert/templates/role.yaml
- charts/victoria-metrics-auth/templates/podsecuritypolicy.yaml
- charts/victoria-metrics-cluster/templates/clusterrole.yaml
- charts/victoria-metrics-cluster/templates/podsecuritypolicy.yaml
- charts/victoria-metrics-cluster/templates/role.yaml
- charts/victoria-metrics-operator/templates/psp.yaml
- charts/victoria-metrics-single/templates/clusterrole.yaml
- charts/victoria-metrics-single/templates/podsecuritypolicy.yaml
- charts/victoria-metrics-single/templates/role.yaml
- charts/victoria-metrics-single/templates/rolebinding.yaml
- adds k8s v1.25 into testing matrix
- replaces `(.Capabilities.APIVersions.Has "policy/v1beta1")` calls with `(.Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy")` to make it compatible with ArgoCD
See #505 for more details.
> charts: fix k8s v1.25 compatibility for PSP

- charts/victoria-metrics-alert/templates/role.yaml
Discovered when trying to use this chart on EKS k8s v1.25 (PSP API removed).  In our case, we are using FluxCD HelmRelease x helm-controller to perform the install.  Possibly helm CLI will ignore the dupe (not sure).
> Fix double "rules" on no-PodSecurityPolicy path

- charts/victoria-metrics-auth/README.md
- charts/victoria-metrics-auth/templates/deployment.yaml
- charts/victoria-metrics-auth/templates/secret.yaml
- charts/victoria-metrics-auth/values.yaml
Currently, this setting is only disabling creating secret which makes vmauth config volume reference invalid and failing deployment.
> charts/vmauth: use `.Values.configMap` value for config volume spec

- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/README.md.gotmpl
- charts/victoria-metrics-alert/templates/alertmanager-deployment.yaml
- charts/victoria-metrics-alert/values.yaml
- remove `alertmanger.replicaCount`
- add a note with workarounds for HA setup
Existing `alertmanager.replicaCount` would only set multiple instance of pod to be running, this does not provide a real HA configuration as users assume when using this. Also, since it uses `Deployment` using multiple replicas will fail to deploy as single PVC cannot be attached to multiple pods for `ReadWriteOnce`. For `ReadWriteMany` it might lead to data corruption since multiple Alertmanager instance might modify the same data.
> charts/vmalert: note that chart does not allow to setup HA Alertmanager

- charts/victoria-metrics-k8s-stack/templates/servicemonitors/grafana.yaml
- charts/victoria-metrics-k8s-stack/templates/servicemonitors/kube-state-metrics.yaml
- charts/victoria-metrics-k8s-stack/templates/servicemonitors/nodeexporter.yaml
The Grafana, kube-state-metrics, and node_exporter subcharts derive the `app.kubernetes.io/name` label in their Service manifests from a helper, usually `{chartname}.name`. If `nameOverride` is given (for whatever reason) then the output of that helper will not match the label value for the VMServiceScrape label selector, which causes it to not work.
Here's a minimum `values.yaml` to reproduce the issue:
```
prometheus-node-exporter:
nameOverride: vm-node-exporter
```
With the current version of the victoria-metrics-k8s-stack the above will cause node_exporter metrics to not work. This PR will fix that. It executes the helper in the context of the subchart so all of the `.Values` and such lookups it does will work as intended.
> Use non-hardcoded `app.kubernetes.io/name` match label in victoria-metrics-k8s-stack VMServiceScrapes

- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
This is adding the `tpl` function to all the spec of the operator. It basically allows us to use helm template language inside the `spec` section of `vmagent`, `vmalert`, `vmcluster` and `vmsingle`. For example, I would prefer to set one global variable for the cluster name (`global.clusterName` for example) and use that as an external labels for both vmagent and vmalert `vmagent.spec.externalLabels.cluster: {{ .Values.global.clusterName }}`.
This is used extensively in kube-prometheus-stack chart, although, it is used in more precise places than what I have here.
Let me know your thoughts.
> [victoria-metrics-k8s-stack]: add tpl to vmagent, vmalert, vmcluster and vmsingle spec

- charts/victoria-metrics-agent/templates/pdb.yaml
- charts/victoria-metrics-alert/templates/server-pdb.yaml
- charts/victoria-metrics-auth/templates/pdb.yaml
- charts/victoria-metrics-cluster/templates/vminsert-pdb.yaml
- charts/victoria-metrics-cluster/templates/vmselect-pdb.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-pdb.yaml
- charts/victoria-metrics-gateway/templates/pdb.yaml
- charts/victoria-metrics-single/templates/pdb.yaml
Hi,
pdb generation on k8s 1.25 is not working properly.
`helm template vm/victoria-metrics-agent --set podDisruptionBudget.enabled=true --api-versions policy/v1/PodDisruptionBudget --kube-version 1.25.9`
```
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
name: release-name-victoria-metrics-agent
namespace: default
labels:
helm.sh/chart: victoria-metrics-agent-0.8.37
app.kubernetes.io/name: victoria-metrics-agent
app.kubernetes.io/instance: release-name
app.kubernetes.io/version: "v1.90.0"
app.kubernetes.io/managed-by: Helm
spec:
selector:
matchLabels:
app.kubernetes.io/name: victoria-metrics-agent
app.kubernetes.io/instance: release-name
```
> fix: Update pdb for k8s 1.25

- charts/victoria-metrics-operator/templates/deployment.yaml
- charts/victoria-metrics-operator/values.yaml
Currently victoria-metrics operator chart (0.21.0) has securityContext option in values.yaml
It sets securityContext for the pod only. But there is no way to set securityContext for the container.
This matter since those contexts have different configuration options (some of them interfere though):
- [container security context](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#securitycontext-v1-core)
- [pod security context](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#podsecuritycontext-v1-core)
For example, there is a really crucial readOnlyRootFilesystem option. It can be set only on container security context level. No way to set it on pod security context level.
Divide securityContext into two parts: pod and container. This breaks …
> victoria-metrics-operator chart: split securityContext

- charts/victoria-metrics-operator/templates/service_scrape.yaml
There are [labels and annotations](https://github.com/VictoriaMetrics/helm-charts/blob/db45a16700c187a0be77ca2566de26b56c8fffa7/charts/victoria-metrics-operator/values.yaml#L155-L156) in values.yaml for VMServiceScrape. Those are unused for VMServiceScrape resource now.
Fix it by merging main labels and annotations with the VMServiceScrape labels and annotations giving precedence to the VMServiceScrape ones.
> operator: fix VMServiceScrape label and annotation templating

- charts/victoria-metrics-cluster/README.md
The page was redirected in October 2022 and now returns an HTTP 404 error.
> Update link to kubernetes.io

- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
Rendering empty securityContext will force deployemtns and STS to be re-created.
> charts/cluster: do not render empty securityContext

- charts/victoria-metrics-cluster/templates/vminsert-hpa.yaml
- charts/victoria-metrics-cluster/templates/vmselect-hpa.yaml
1. Upgrade to new apiVersion. autoscaling/v2beta2 is no longer supported as of 1.26, and has been deprecated for a few versions now
2. Allow specifying the apiVersion in values. This is a fairly common pattern and will allow users to workaround this change.
Resolves #514
> Update to new HPA apiVersion, and allow specifying in values

- charts/victoria-metrics-anomaly/README.md
- charts/victoria-metrics-anomaly/templates/configmap.yaml
- charts/victoria-metrics-anomaly/values.yaml
- hack/helm/victoria-metrics-anomaly.yaml
- hack/vmanomaly-lint-hack.yaml
Update configuration to template `pull` and `push` sections only in case configuration for these is defined. Fixes compatibility with latest vmanomaly config version.
> charts/victoria-metrics-anomaly: make monitoring config more configurable

- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
Fixes: https://github.com/VictoriaMetrics/helm-charts/issues/575
> charts/victoria-metrics-cluster: fix indent for vmselect statefulset

- charts/victoria-metrics-agent/templates/extra-objects.yaml
- charts/victoria-metrics-agent/values.yaml
Allow pass through of additional objects, to allow for such things as secrets to be mounted.
> Feat: Add custom objects to vma helm charts

- charts/victoria-logs-single/templates/server-statefulset.yaml
Due to improper end block location part of manifest was rendered even when STS was set to false.
> charts/victoria-logs-single: fix STS render when using statefulset is disabled

- charts/victoria-logs-single/templates/server-deployment.yaml
- charts/victoria-logs-single/templates/server-statefulset.yaml
- charts/victoria-metrics-alert/templates/alertmanager-deployment.yaml
- charts/victoria-metrics-alert/templates/server-deployment.yaml
- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-single/templates/_helpers.tpl
- charts/victoria-metrics-single/templates/server-deployment.yaml
- charts/victoria-metrics-single/templates/server-statefulset.yaml
fix https://github.com/VictoriaMetrics/helm-charts/issues/455
`securityContext` should be used for containers, `podSecurityContext` should be used for pod
> fix misused securityContext and podSecurityContext

- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-cluster/values.yaml
For some reason topologySpreadConstraints field exists in vmselect-deployment, but missing in other templates. For that reason, I'm adding it back, to keep templates consistent.
> [vmstorage, vminsert] Add topologySpreadConstraints

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
- charts/victoria-metrics-k8s-stack/values.yaml
- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/templates/_helpers.tpl
- charts/victoria-metrics-operator/templates/uninstall_hook.yaml
- charts/victoria-metrics-operator/values.yaml
I think the right way to fix https://github.com/VictoriaMetrics/helm-charts/issues/548 is moving the cleanup job to operator, instead of have a second job in operator.
But there will be version dependency for victoria-metrics-k8s-stack, it will only have cleanup job when having new operator version.
> move clean up cr job to operator chart

- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
If instead of replicas in notifiers add only a service, then alerts are sent to only one alertmanager and this is a problem since alerts in the alertmanager cluster are not synchronized, unlike silence.
> [victoria-metrics-k8s-stack]:vmalert notifiers and replicas of alertmanager

- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-views-global.yaml
the currently, the dashboards use kube_pod_container_resource_requests metric with a constraint on unit=byte to calculate memory maximums. 
this becomes misleading when also setting the "ephemeral storage" resource, because the unit is also bytes, but the resource is ephemeral_storage, not memory, resulting in incorrect values
> fix grafana dashboards so ephemeral_storage does not mess with memory query

- charts/victoria-metrics-operator/templates/service_scrape.yaml
Fix [option name](https://docs.victoriametrics.com/operator/api.html#endpoint) for victoria-metrics-operator VMServiceScrape
> Fix relabelConfigs for operator scrape

- charts/victoria-metrics-alert/values.yaml
Hello, guys!
Pretty simple fix. Found this while I was trying out the chart! 
Seems like the placement of the imagePullSecrets for the server configuration is wrong in the default values file.
Best Regards,
Ramon Borges
> fix: imagePullSecrets was in the wrong place in the default values file

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
Now `remoteWrite.url` for VMAlert is correctly generated considering endpoint, name, port and http.pathPrefix of VMAgent if `vmalert.remoteWriteVMAgent=true`
> Fixed behavior of `vmalert.remoteWriteVMAgent`

- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/templates/_helpers.tpl
- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
From pod labels removed dynamic label `helm.sh/chart` to avoid restarting every time the chart is updated without changing the pods parameters. 
**Note that this time it will lead the pods restart** 
issue: #695
> From pod labels removed dynamic label `helm.sh/chart`

- charts/victoria-metrics-operator/templates/cluster_role.yaml
Hello VictoriaMetrics team,
we discovered that the operator chart RBAC misses the following permission after operator itself was modified https://github.com/VictoriaMetrics/operator/pull/763
Thanks
> added endpointslices permissions to operator rbac clusterrole

- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-single/Chart.yaml
Updates in order to release fix from https://github.com/VictoriaMetrics/helm-charts/pull/712 and address https://github.com/VictoriaMetrics/helm-charts/issues/728
> {single,cluster}: bump charts version for release

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/values.yaml
scheduler port default value was still set to the deprecated value of 10251 in the k8s-stack chart
fixes #339
> fix: change default scheduler port in k8s-stack scrapeservice

- charts/victoria-metrics-k8s-stack/hack/sync_rules.py
- charts/victoria-metrics-k8s-stack/values.yaml
Hi,
the kube-prometheus-stack chart allows to disable individual alerts that it ships.
This was added to their sync_rules.py almost two years ago and was something i really missed in this chart.
This merge request will adjust the sync_rules.py to also include the conditions to disable individual rules.
I did test this locally by generating the rules with the make file and running helm template to validate that the chart renders correctly.
If you want i can also generate the rules in this MR but i thought that is part of the release process, thats why i did not yet include it. Let me know if i should add the new rules to this MR.
Maybe it would also be a good idea to bring the script in sync with the latest version of the kube-prometheus-stack chart: …
> update sync_rules.py to allow disabling individual alerts

- charts/victoria-metrics-cluster/templates/_helpers.tpl
If the statefulset name length is 63, the pod name length of the statefulset is more than 63. The Pods' names take the form `<statefulset name>-<ordinal index>`.
So this PR limits the statefulset name max length to 60.
> Fix: the statefulset pod name length is more than 63

- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
Previously, using `extraVolumes` would trigger an error:
```
Error: UPGRADE FAILED: template: templates/vminsert-deployment.yaml:168:12: executing "templates/vminsert-deployment.yaml" at <include "chart.license.volume" .>: error calling include: template: templates/_helpers.tpl:297:18: executing "chart.license.volume" at <.Values.license.secret.name>: can't evaluate field Values in type []interface {}
```
Caused by using `.` from unexpected context from `with` clause.
> victoria-metrics-cluster: fix vminsert template for extra volumes

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/hack/sync_grafana_dashboards.py
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/alertmanager-overview.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/backupmanager.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/grafana-overview.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-system-coredns.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-views-global.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-views-namespaces.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-views-pods.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/operator.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/victoriametrics-cluster.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/victoriametrics.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/vmagent.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/vmalert.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
In *victoria-metrics-k8s-stack* Helm Chart, when values define `grafanaOperatorDashboardsFormat.enabled=true`, special `GrafanaDashboard` CRs get rendered that provide dashboards to Grafana Operator (https://grafana-operator.github.io/grafana-operator/). But those CRs don't get imported into Grafana instance when the Grafana Operator is not deployed to the same k8s namespace as the victoria-metrics-k8s-stack chart is, since `GrafanaDashboard` CRs are created in this namespace.
The provided patch allows overriding an additional boolean attribute in the chart values: `grafanaOperatorDashboardsFormat.allowCrossNamespaceImport` which is false by default. When set to true, the created `GrafanaDashboard` CRs will also contain this attribute and Grafana Operator will import them from a namespace …
> victoria-metrics-k8s-stack: optional allowCrossNamespaceImport in GrafanaDashboard(s)

- Makefile
Unfortunately, in the following PR https://github.com/VictoriaMetrics/helm-charts/pull/790 that was already merged into master, there is a syntax error in the Makefile. I didn't use Makefiles for decades so I forgot that tabs are a must in the target definitions, but I never even knew that they must not be used before the targets, in the instructions that are evaluated during parsing of Makefile. So this patch fixes that. The faulty Makefile is OK when CONTAINER variable was either docker or podman, but when something else is used, I got the following output:
```
[peter@sun vm-helm-charts]$ CONTAINER=faulty make sync-dashboards
Makefile:18: *** recipe commences before first target.  Stop.
```
After this patch, the values docker and podman still work as expected, and any other value give …
> Fix Makefile: use spaces instead of tabs in instructions before targets

- charts/victoria-metrics-agent/templates/_helpers.tpl
- charts/victoria-metrics-alert/templates/_helpers.tpl
- charts/victoria-metrics-anomaly/templates/_helpers.tpl
- charts/victoria-metrics-auth/templates/_helpers.tpl
- charts/victoria-metrics-cluster/templates/_helpers.tpl
- charts/victoria-metrics-gateway/templates/_helpers.tpl
- charts/victoria-metrics-single/templates/_helpers.tpl
Follow-up for https://github.com/VictoriaMetrics/helm-charts/pull/797
Remove `secret.key` reference as it does not actually exist in k8s resource.
> license configuration: remove `secret.key` references for license volumes

- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
The chart currently fails to deploy for me due to this error.
See - https://github.com/VictoriaMetrics/helm-charts/issues/843
> Remove invalid `scheme` for `tcpSocket` `livenessProbe`s

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/values.yaml
This is useful to lower vmagent's memory usage by default by sacrificing built-in relabeling debug UI.
> charts/victoria-metrics-k8s-stack: add `promscrape.dropOriginalLabels` by default

- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/templates/alertmanager-deployment.yaml
- charts/victoria-metrics-alert/values.yaml
Add the ability to add extra arguments, containers, volumes, and volume mounts to the alertmanager deployment.
I implemented this change to able to add a sidecar to the alertmanager for automatic config reloading, and decided to round it out with the features from the server deployment.
> Make alertmanager deployment more extensible

- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/Chart.yaml
- charts/victoria-metrics-alert/templates/alertmanager-deployment.yaml
- charts/victoria-metrics-alert/values.yaml
Allow overriding Alertmanager listen addr to support IPv6-only clusters. See: https://github.com/VictoriaMetrics/helm-charts/issues/856
> charts/vmalert: allow overriding alertmanager listen addr

- .github/workflows/run-testing.yaml
- hack/helm/victoria-metrics-anomaly.yaml
Creating a secret when testing any chart for simplicity. Currently, only vmanomaly chart needs the license key to for testing.
FYI: @Cambaza @fred-navruzov
> ci: setup a license for vmanomaly chart testing

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
Fixes templating of remoteWrite URLs in case built-in VMSingle and VMCluster are both disabled. See: https://github.com/VictoriaMetrics/helm-charts/issues/865
P.S. I've tested changes on a local cluster and it works just as expected while it fails in CI. I'll investigate why CI fails for k8s-stack and address this in a separate PR.
> charts/victoria-metrics-k8s-stack: fix remoteWrite URLs templating

- charts/victoria-metrics-auth/CHANGELOG.md
- charts/victoria-metrics-auth/templates/deployment.yaml
it allows to properly configure tls configuration for vmauth chart https://github.com/VictoriaMetrics/helm-charts/issues/528
> charts/vmauth: changes ready httpGet probe with tcpSocket

- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/README.md.gotmpl
As it is stated in the [kube-state-metrics/Helm Chart](https://github.com/kubernetes/kube-state-metrics/tree/main#helm-chart)
> Starting from the kube-state-metrics chart v2.13.3 (kube-state-metrics image v1.9.8), the official [Helm chart](https://artifacthub.io/packages/helm/prometheus-community/kube-state-metrics/) is maintained in [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics).
So, link to the repository should be updated.
> Update link to kube-state-metrics

- .github/workflows/run-testing.yaml
- README.md
drop k8s 1.24.x and add latest version
https://endoflife.date/kubernetes#:~:text=Kubernetes%20is%20an%20open%2Dsource,deployment%2C%20scaling%2C%20and%20management.&text=Kubernetes%20follows%20an%20N%2D2,a%2015%2Dweek%20release%20cycle.
>Kubernetes follows an N-2 support policy (meaning that the 3 most recent minor versions receive security and bug fixes) along with a [15-week release cycle](https://github.com/kubernetes/enhancements/tree/master/keps/sig-release/2572-release-cadence). This results in a release being supported for 14 months (12 months of support and 2 months of upgrade period).
> ci: update install-chart ci k8s version

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/templates/_helpers.tpl
- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/templates/_helpers.tpl
- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/templates/_helpers.tpl
- charts/victoria-metrics-anomaly/templates/_helpers.tpl
- charts/victoria-metrics-auth/CHANGELOG.md
- charts/victoria-metrics-auth/templates/_helpers.tpl
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/templates/_helpers.tpl
- charts/victoria-metrics-gateway/templates/_helpers.tpl
- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/templates/_helpers.tpl
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/templates/_helpers.tpl
Properly truncate "app.kubernetes.io/managed-by" and "app.kubernetes.io/instance" labels for long release names. Apply limit of 63 chars for all truncated labels.
This is a follow-up to cd6921b33551bcc274692d8fdeed890f3b441006
> charts: properly truncate labels for long release names

- charts/victoria-metrics-operator/templates/service_account.yaml
The prior configuration allowed the generation of an empty service account yaml file with indented labels or annotations.
> Update service_account.yaml with proper end statement placement

- charts/victoria-metrics-operator/templates/crd_clusterrole.yaml
- charts/victoria-metrics-operator/values.yaml
Kubernetes has view and admin roles that aggregate permissions from
other clusterroles that have the right annotations.
The advantage to this is that the view clusterrole doesn't need to be
edited whenever a new CRD is installed, but can still be extended so
view and admin also provide view and admin access to new CRDs.
The functionality is similar to drop-in files in systemd and other
linux/unix tooling.
The change adds the aggregate role functionality to the victoria-metrics-operator
helm chart. So whenever the CRDs are installed the user can also choose
to install the clusterroles that extend the view and admin default
clusterroles.
> feat(crd): view and admin aggregate roles for CRDs

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/Chart.yaml
- charts/victoria-logs-single/README.md
- charts/victoria-logs-single/templates/_helpers.tpl
- charts/victoria-logs-single/templates/server-deployment.yaml
- charts/victoria-logs-single/templates/server-statefulset.yaml
- charts/victoria-logs-single/values.yaml
- update VictoriaLogs to v0.8.0
- Move parameters used for service name templating from ".Values.server" to ".Values.global.victoriaLogs". This is required to make a seamless integration with Fluent Bit output. Moving values to ".Values.global" allows to ensure that service name rendered in subchart will be using the same context as parent chart.
- Include k8s namespace in default stream fields configuration to make it easier to filter logs.
- Remove unused "scrape" template.
> charts/victoria-logs-single: chart improvements, update to 0.8.0

- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
fixing https://github.com/VictoriaMetrics/helm-charts/issues/1060
> victoria-metrics-cluster: Port name fix for custom port name in readiness and liveness check

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/values.yaml
Adding "cluster" label by default is only useful for multi-cluster setups, which is a rare case. It is also hard to override this value to an empty map due to merge logic in Helm.
> charts/victoria-metrics-k8s-stack: do not add "cluster" label by default

- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/templates/deployment.yaml
- charts/victoria-metrics-agent/templates/statefulset.yaml
- charts/victoria-metrics-agent/values.yaml
- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/templates/server-deployment.yaml
- charts/victoria-metrics-alert/values.yaml
- charts/victoria-metrics-auth/CHANGELOG.md
- charts/victoria-metrics-auth/templates/deployment.yaml
- charts/victoria-metrics-auth/values.yaml
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/templates/_helpers.tpl
- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-cluster/values.yaml
- charts/victoria-metrics-gateway/CHANGELOG.md
- charts/victoria-metrics-gateway/templates/deployment.yaml
- charts/victoria-metrics-gateway/values.yaml
- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/templates/deployment.yaml
- charts/victoria-metrics-operator/values.yaml
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/templates/server-deployment.yaml
- charts/victoria-metrics-single/templates/server-statefulset.yaml
- charts/victoria-metrics-single/values.yaml
This change syncs the image tags with `.Chart.AppVersion` directly, and makes it possible to upgrade chart without modifying image tag for users who use customized images with suffix `-enterprise` or `-scratch`. 
But it brings breaking change for user who is using non-default tags, they need to remove the `-cluster` suffix in tags.
> victoria-metrics-cluster: change components image template

- .github/workflows/run-testing.yaml
Helm only outputs a warning if there are schema issues, but will continue anyway. This adds a step before install that performs validation against the k8s server before proceeding with the helm chart install.
Would be nice to have it in the linting CI, however this is the only place in CI that we have a cluster to work with. In order to validate the manifests properly, `--dry-run=server` is required.
~Not sure if you would want it as a linting step, so I've left it as a draft PR.~ actually, since the testing runs on PR's and on Push anyway, that seems fine.
I've updated so that it verifies with `kubectl` post-install since we will rely on CRDs for some charts. I'm not able to test the CI directly, but it seems we setup a k3d cluster for each chart, so it's safe to use `--skip-clean-up` …
> Validate manifests with `kubectl` in CI

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/Chart.yaml
- charts/victoria-logs-single/templates/NOTES.txt
Fix label selector which is printed in post installation notes.
> charts/victoria-logs-single: fix command printed after chart installation

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
Based on the documentation in the values file and in the [operator migration documentation](https://docs.victoriametrics.com/operator/migration/#objects-conversion). I believe that this should be set to false initially. This is similar to the [values in the operator stand alone chart](https://github.com/VictoriaMetrics/helm-charts/blob/dae3850b4cd9b1ca8a742a72dde9e0be0ddffc11/charts/victoria-metrics-operator/values.yaml#L69) where it is set to disabled false.
```yaml
operator:
disable_prometheus_converter: true
```
> Prometheus converter disabled by default in stack chart

- .github/workflows/release.yaml
current version of annotations could break a release and requires a strict format of changelog entries
Well known solution for it use some python script. But it brings additional complexity
> ci: disable artifacthub changes annotations

- charts/victoria-metrics-k8s-stack/templates/serviceaccount.yaml
When we only use `helm template`, the `metadata.namespace` field will not be rendered, which can cause GitOps sync operations to fail.
> fix: add metadata.namespace in serviceaccount template

- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/Chart.yaml
- charts/victoria-metrics-single/templates/_helpers.tpl
- charts/victoria-metrics-single/templates/server-deployment.yaml
- charts/victoria-metrics-single/templates/server-statefulset.yaml
This PR updates the templates helper to use a double hyphen for the `license` and `licenseFile` parameters, to match the double hyphen used for other parameters provided to the container.
> fix: Use double hyphen for license and licenseFile parameters

- charts/victoria-metrics-distributed/CHANGELOG.md
- charts/victoria-metrics-distributed/Chart.lock
- charts/victoria-metrics-distributed/Chart.yaml
- charts/victoria-metrics-distributed/README.md
- charts/victoria-metrics-distributed/README.md.gotmpl
- charts/victoria-metrics-distributed/templates/_helpers.tpl
- charts/victoria-metrics-distributed/templates/per-az/vmagent.yaml
- charts/victoria-metrics-distributed/values.yaml
Disable multitenancy mode by default since it increases memory usage in vmagent, and most of the users not use it.
See how to enable it in https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-distributed#how-to-use-multitenancy.
> victoria-metrics-distributed: fix default multitenancy mode and disable it by default

- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/Chart.yaml
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/templates/alertmanager-deployment.yaml
- charts/victoria-metrics-alert/values.yaml
- hack/vmalert-lint-hack.yaml
This PR adds a user-configurable envFrom option specifically for the alertmanager Deployment. This parameter is already supported in the alert server Deployment.
> feat: Support envFrom in alertmanager Deployment

- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/templates/vpa.yaml
- charts/victoria-metrics-alert/values.yaml
Reason for this change - For components like VMAlert where scaling horizontally doesn't solve issues with processing alerts, scaling vertically is the only option to deal with scaling problems. 
Tested locally by installing VMAlert with and without VPA enabled from values file and both the times the installation worked.
> feat: VPA for VMAlert

- charts/victoria-metrics-k8s-stack/files/rules/generated/alertmanager.rules.yaml
- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/templates/uninstall_hook.yaml
.Capabilities.KubeVersion.Minor returns version with plus sign, but for example there is no such tag as 1.27+ for bitnami/kubectl image (https://hub.docker.com/r/bitnami/kubectl/tags?page=&page_size=&ordering=&name=1.27%2B).
> Fix image tag in victoria-metrics-operator/templates/uninstall_hook.yaml

- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/templates/clusterrole.yaml
- charts/victoria-metrics-agent/templates/clusterrolebinding.yaml
Reported here - https://github.com/VictoriaMetrics/helm-charts/issues/1178
Issue Summary
On setting the rbac to render Role and RoleBindings, namespace is not rendered in metadata
```
rbac:
create: true
namespaced: true
```
This causes the helm chart to fail installation.
> Fix vmagent ClusterRole and ClusterRoleBinding to correctly render Role and RoleBinding

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/templates/grafana/datasource.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
We have a proxy inbetween grafana and the victoria metrics prometheus endpoint. This proxy handles authentication and authorization based on forwarded oauth identities. As all datasources available in Grafana can be used by everbody, I need to be able to remove the default datasource, so that there is not direct connection to the prometheus endpoint.
This was also requested by another guy in #520
> Allow to disable default grafana datasource

- charts/victoria-metrics-k8s-stack/values.yaml
It is already possible to specify custom selector for KSM metrics by using `.Values.kube-state-metrics.vmServiceScrape.spec` so comment is not relevant.
> charts/victoria-metrics-k8s-stack: remove outdated comment

- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/templates/vminsert-ingress.yaml
This allows to override port number for ingestion protocols such as openTSDB, Graphite and others.
> charts/victoria-metrics-cluster: fix templating of ingress port

- charts/victoria-metrics-operator/templates/webhook.yaml
The `Issuer` and `ValidatingWebhookConfiguration` resources are getting glued together.
> Fix cert-manager managed webhooks

- charts/victoria-metrics-operator/Chart.lock
- charts/victoria-metrics-operator/templates/_helpers.tpl
- charts/victoria-metrics-operator/templates/cluster_role.yaml
- charts/victoria-metrics-operator/templates/role.yaml
- charts/victoria-metrics-operator/values.yaml
Follow-up for https://github.com/VictoriaMetrics/helm-charts/pull/1310
> charts/victoria-metrics-operator: fix CRD naming in RBAC

- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/Chart.yaml
- charts/victoria-metrics-common/templates/_enterprise.tpl
- charts/victoria-metrics-common/templates/_helpers.tpl
- charts/victoria-metrics-common/templates/_image.tpl
- charts/victoria-metrics-common/templates/_ingress.tpl
- charts/victoria-metrics-common/templates/_pod.tpl
- charts/victoria-metrics-common/templates/_service.tpl
- Added `vm.service` to construct vmoperator-managed service name
- Added `vm.url` to construct vmoperator-managed service base url
- Added `vm.name` for chart name
- Added `vm.fullname` which is actively used in resource name construction
- Added `vm.chart` to construct chart name label value
- Added `vm.labels` for common labels
- Added `vm.sa.name` for service account name
- Added `vm.metaLabels` for compatibility with most of the charts
- Added `vm.release` for release name
- Added `vm.selectorLabels` for common selector labels
- Expect built-in variables in both root and `.helm` context
> common: added more templates

- charts/victoria-metrics-anomaly/values.yaml
vmanomaly automatically appends `/insert` and `/select` prefixes, it is not needed be set manually.
> charts/victoria-metrics-anomaly: fix example URL in comments

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/values.yaml
can be related to https://github.com/VictoriaMetrics/helm-charts/issues/1419
do not create operator's service monitor, when it's already provided by operator's chart and just requires a `victoria-metrics-operator.serviceMonitor.enabled` toggle to be set to `true`
> use operator's own service monitor

- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/templates/servicemonitors.yaml
- fixed resources templating for vmstorage in victoria-metrics-cluster chart
- drop empty "endpoints" from spec to support switching to different scrape config types
> cluster bugfix and drop empty endpoints from scrape

- charts/victoria-metrics-alert/templates/_helpers.tpl
AM does not use VictoriaMetrics' licensing flags, so remove templating of these flags.
> charts/victoria-metrics-alert: remove license args for AM

- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/templates/service.yaml
- charts/victoria-metrics-operator/templates/webhook.yaml
made service port for webhook the same as pod port
can be related to 
https://github.com/VictoriaMetrics/operator/issues/1094
> updated webhook service port

- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/Chart.yaml
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/Chart.yaml
- charts/victoria-metrics-common/templates/_helpers.tpl
- charts/victoria-metrics-common/templates/_service.tpl
- charts/victoria-metrics-distributed/CHANGELOG.md
- charts/victoria-metrics-distributed/Chart.lock
- charts/victoria-metrics-distributed/Chart.yaml
- charts/victoria-metrics-distributed/templates/grafana-datasource.yaml
- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.lock
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboard.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/datasource.yaml
- charts/victoria-metrics-k8s-stack/templates/rules/additionalVictoriaMetricsRules.yml
- charts/victoria-metrics-k8s-stack/templates/servicemonitors.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/custom-templates.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/monzo-template.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmalert/custom-templates.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmalert/notifiers.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/templates/_helpers.tpl
- charts/victoria-metrics-operator/templates/crb.yaml
- charts/victoria-metrics-operator/templates/role.yaml
- charts/victoria-metrics-operator/templates/webhook.yaml
- do not truncate datasource, dashboard, rule, config, alert template names
- some typo fixes in common chart
- append global.cluster.dnsDomain to domain in common chart. related issue https://github.com/VictoriaMetrics/helm-charts/issues/1455
- added common chart to k8s-stack directly, related issue https://github.com/VictoriaMetrics/helm-charts/issues/1456
- fixed jobLabel for node-exporter, related issue https://github.com/VictoriaMetrics/helm-charts/issues/1458
- fix operator Role creation when only watching own namespace using `watchNamespaces`
> do not truncate names of resources to prevent collision

- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
in the victoria-metrics-cluster chart.
This is required otherwise rendering the chart will result in the following:
```
Error: template: victoria-metrics-cluster/charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml:61:32: executing "victoria-metrics-cluster/charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml" at <include "vm.port.from.flag" (dict "flag" .)>: error calling include: template: victoria-metrics-cluster/charts/victoria-metrics-auth/charts/victoria-metrics-common/templates/_pod.tpl:4:44: executing "vm.port.from.flag" at <.>: wrong type for value; expected string; got chartutil.Values
```
> Fix the clusternativeListenAddr port for vmselect

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/README.md
- charts/victoria-metrics-anomaly/templates/configmap.yaml
- charts/victoria-metrics-anomaly/values.yaml
**Description**
This pull request introduces the ability to add annotations to the anomaly ConfigMap. Annotations are crucial for integrating the ConfigMap with tools like Vault, among others. By allowing annotations, this change enhances the flexibility of the ConfigMap, enabling seamless integrations with external systems that rely on metadata
> Enable to add annotations to vmanomaly  configMap

- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/Chart.yaml
- charts/victoria-metrics-common/templates/_enterprise.tpl
- charts/victoria-metrics-common/templates/_image.tpl
- charts/victoria-metrics-common/templates/_service.tpl
release common functions, that are useful for not managed by operator resources
> common: new release with enterprise and image related functions

- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/Chart.yaml
- charts/victoria-metrics-common/templates/_enterprise.tpl
- charts/victoria-metrics-common/templates/_image.tpl
- Do not use image variant if custom image tag is set in `vm.image` template
- Support multiple license flag styles, which are different for vmanomaly and other services
> common: new release with templates fixes

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/Chart.lock
- charts/victoria-logs-single/Chart.yaml
- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.lock
- charts/victoria-metrics-anomaly/Chart.yaml
- charts/victoria-metrics-anomaly/templates/_helpers.tpl
release logs and anomaly charts
> release logs and anomaly charts with fixes

- charts/victoria-metrics-distributed/templates/vmauth-read.yaml
Hello,
Align the vmauth-read template with the vmauth-write template.
It fixes for me the issue #1510 
after the patch I have the appropriate vmauth-global-read-vmdistributed-vm-distributed definition : 
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
annotations:
meta.helm.sh/release-name: vmdistributed
meta.helm.sh/release-namespace: vm
operator.victoriametrics/last-applied-spec: '{"image":{"repository":"docker.io/victoriametrics/vmauth","tag":"v1.103.0","pullPolicy":"IfNotPresent"},"resources":{},"unauthorizedAccessConfig":[{"src_paths":["/select/.+"],"url_prefix":["http://vmauth-vmauth-read-proxy-aisle-a:8427/","http://vmauth-vmauth-read-proxy-aisle-b:8427/"],"load_balancing_policy":"first_available"}],"ip_filters":{}}'
creationTimestamp: …
```
> [victoria-metrics-distributed] align vmauth-read with vmauth-write template

- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/Chart.lock
- charts/victoria-metrics-operator/templates/_helpers.tpl
- charts/victoria-metrics-operator/templates/service.yaml
- charts/victoria-metrics-operator/templates/webhook.yaml
- charts/victoria-metrics-operator/values.yaml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1506
> operator: configurable webhook port

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/templates/ingress.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
related issue https://github.com/VictoriaMetrics/helm-charts/issues/1260
> k8s-stack: use path prefix from args as a default ingress path

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
https://victoriametrics.slack.com/archives/CTC488T1P/p1726776490053099?thread_ts=1725540517.623349&cid=CTC488T1P
> k8s-stack: check `notifier.blackhole` flag if no notifiers are set in vmalert

- charts/victoria-metrics-operator/templates/uninstall_hook.yaml
The current implementation of the operator's cleanup job uses the Helm's `keys` function to find which custom resources should be deleted. However, the array returned by `keys` isn't in a predictable order, and may change each time a user runs a Helm command.
This commit fixes that issue by sorting the array returned by `keys` before using it. It utilizes a Helm's function `sortAlpha` for this purpose.
> sort targets of operator's cleanup job

- charts/victoria-logs-single/Chart.lock
- charts/victoria-logs-single/Chart.yaml
- charts/victoria-logs-single/values.yaml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1525
> fixed default fluentbit config, use headers instead of query args

- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-agent/README.md
- charts/victoria-metrics-agent/README.md.gotmpl
- charts/victoria-metrics-agent/templates/_helpers.tpl
- charts/victoria-metrics-agent/templates/configmap.yaml
- charts/victoria-metrics-agent/templates/deployment.yaml
- charts/victoria-metrics-agent/templates/statefulset.yaml
- charts/victoria-metrics-agent/values.yaml
- hack/helm/victoria-metrics-agent/e2e/simple.yaml
- hack/helm/victoria-metrics-agent/lint/cluster.yaml
- hack/helm/victoria-metrics-agent/lint/simple.yaml
removed `multiTenantUrls` as it's deprecated in VictoriaMetrics 1.102.0
added `remoteWrite` param, which replaces `remoteWriteUrls`and besides adding`remoteWrite.*` prefixed cmd flags to vmagent process also generates config map with content of values if values types are array or map. e.g:
```
remoteWrite:
- url: http://localhost/api/v1/write
urlRelabelConfig:
- action: keep
source_labels: [env]
regex: "dev"
```
`--remoteWrite.url=http://localhost/api/v1/write` and `--remoteWrite.urlRelabelConfig=/config/rw/0-urlRelabelConfig.yaml` flags will be added together with config map, which contains
```
data:
0-urlRelabelConfig.yaml: |
- action: keep
source_labels: [env]
regex: "dev"
```
which is mounted to a pod
> vmagent: added remoteWrite param as a replacement for remoteWriteUrls

- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/Chart.yaml
- charts/victoria-metrics-auth/CHANGELOG.md
- charts/victoria-metrics-auth/Chart.yaml
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-distributed/CHANGELOG.md
- charts/victoria-metrics-distributed/Chart.yaml
- charts/victoria-metrics-gateway/CHANGELOG.md
- charts/victoria-metrics-gateway/Chart.yaml
- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/Chart.yaml
I followed https://docs.victoriametrics.com/release-guide/#helm-charts
> bump to 1.104.0

- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-cluster/templates/_helpers.tpl
- charts/victoria-metrics-cluster/values.yaml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1549
Added `vminsert.excludeStorageIDs` list param, which allows to specify storage nodes, that will be excluded from vminsert storage nodes list
> victoria-metrics-cluster: allow excluding vmstorage node from vminsert's storage node list

- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-cluster/values.yaml
- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
- charts/victoria-metrics-k8s-stack/values.yaml
- generate tag name from chart appversion
- removed unused rbac values from cluster chart. fixes https://github.com/VictoriaMetrics/helm-charts/issues/1554
> k8s-stack: generate vm components tag from app version by default

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/values.yaml
- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/Chart.yaml
- charts/victoria-metrics-operator/README.md
- charts/victoria-metrics-operator/templates/deployment.yaml
- charts/victoria-metrics-operator/templates/uninstall_hook.yaml
- charts/victoria-metrics-operator/values.yaml
- alertmanaget default image upgrade. fixes https://github.com/VictoriaMetrics/helm-charts/issues/1569
- added terminationGracePeriodSeconds and licecycle. fixes https://github.com/VictoriaMetrics/helm-charts/issues/1563
- added configurable resources for operator. fixes https://github.com/VictoriaMetrics/helm-charts/issues/1571
- fail if operator cleanup image tag is not string. fixes https://github.com/VictoriaMetrics/helm-charts/issues/1566
> k8s-stack: alertmanager upgrade 0.27.0 and other minor bugfixes and improvements

- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/Chart.yaml
- charts/victoria-metrics-common/templates/_helpers.tpl
added human readable error for old helm versions to prevent repeatable issues like:
- https://github.com/VictoriaMetrics/helm-charts/issues/1578
- https://github.com/VictoriaMetrics/helm-charts/issues/1537
- https://github.com/VictoriaMetrics/helm-charts/issues/1436
- https://github.com/VictoriaMetrics/helm-charts/issues/1413
- https://github.com/VictoriaMetrics/helm-charts/issues/1352
> common: readable error on helm older than 3.14

- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/Chart.yaml
- charts/victoria-metrics-common/templates/_helpers.tpl
- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
currenly default name prefix override can be extracted from:
- global.fullnameOverride
- global.<Chart.Name>.fullnameOverride:
- fullnameOverride
- <appSection>.name
Added `<appSection>.fullnameOverride` additionally to fix backward compatibility issue for cluster chart
> common: use <appSection>.fullnameOverride as alternative source for resource name prefix

- charts/victoria-metrics-agent/Chart.lock
- charts/victoria-metrics-alert/Chart.lock
- charts/victoria-metrics-anomaly/Chart.lock
- charts/victoria-metrics-anomaly/README.md
- charts/victoria-metrics-auth/Chart.lock
- charts/victoria-metrics-distributed/Chart.lock
- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.lock
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/charts/crds
- charts/victoria-metrics-k8s-stack/values.yaml
- charts/victoria-metrics-operator/README.md
- charts/victoria-metrics-single/Chart.lock
moved CRDs to operators `crds` folder to avoid importing them in both k8s-stack and operator charts
> k8s-stack: removed CRDs subchart as they are already included in operator

- charts/victoria-logs-single/templates/extra-outputs.yaml
- charts/victoria-logs-single/templates/server-deployment.yaml
- charts/victoria-logs-single/values.yaml
use k8s service url while using deployments for vlogs or replica count == 1
fixed fluent-bit hot-reload when victorialogs relicacount changes
added temporary workaround till https://github.com/fluent/helm-charts/pull/561 is merged
> vlogs: use service url for single replica and deployment

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/templates/server-deployment.yaml
- charts/victoria-logs-single/templates/server-pvc.yaml
- charts/victoria-logs-single/values.yaml
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/templates/server-deployment.yaml
- charts/victoria-metrics-single/templates/server-pvc.yaml
- charts/victoria-metrics-single/values.yaml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1646
> single: allow overriding pvc names for deployment

- .github/workflows/release.yaml
currently all latest OCI packages are overwriting during each run of release job, which causes issues for users, who are using OCI
> ci: remove already published packages to prevent OCI releases from overwriting

- charts/victoria-metrics-operator/charts/crds/crds/crd.yaml
solve the issue that prevent correct upgrade or install operator's crd
> operator's crd: fix typo in crd field description

- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/README.md.gotmpl
Config example refers to disabling sidecar container but still uses `enabled: true`. Fixed inconsistency between description and config.
> charts/victoria-metrics-k8s-stack: fix config example for init container

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/custom-templates.yaml
`indent` does not add a new line char, which results into templating labels right after `labels`:
```
labels: app.kubernetes...
```
`nindent` adds a new line so labels are properly templated starting from the next line.
> charts/k8s-stack: fix templating of the labels for VMAlertmanager

- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/templates/deployment.yaml
- charts/victoria-metrics-agent/templates/statefulset.yaml
- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/templates/alertmanager-deployment.yaml
- charts/victoria-metrics-alert/templates/server-deployment.yaml
- charts/victoria-metrics-auth/CHANGELOG.md
- charts/victoria-metrics-auth/templates/deployment.yaml
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-gateway/CHANGELOG.md
- charts/victoria-metrics-gateway/templates/deployment.yaml
- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/templates/deployment.yaml
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/templates/server-deployment.yaml
- charts/victoria-metrics-single/templates/server-statefulset.yaml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1683
> remove serviceAccountName from Deployment and StatefulSet, when it's disabled

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/Chart.yaml
- charts/victoria-logs-single/templates/extra-outputs.yaml
- charts/victoria-logs-single/values.yaml
- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/values.yaml
- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/values.yaml
- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/values.yaml
- charts/victoria-metrics-auth/CHANGELOG.md
- charts/victoria-metrics-auth/values.yaml
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/values.yaml
- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/Chart.yaml
- charts/victoria-metrics-common/templates/_pod.tpl
- charts/victoria-metrics-distributed/CHANGELOG.md
- charts/victoria-metrics-distributed/Chart.lock
- charts/victoria-metrics-distributed/Chart.yaml
- charts/victoria-metrics-distributed/values.yaml
- charts/victoria-metrics-gateway/CHANGELOG.md
- charts/victoria-metrics-gateway/values.yaml
- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/values.yaml
- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/values.yaml
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/values.yaml
- set default DNS domain in all charts. fixes https://github.com/VictoriaMetrics/helm-charts/issues/1626
- common: fixed boolean args rendering
- vlogs: made fields configurable. fixes https://github.com/VictoriaMetrics/helm-charts/issues/1695
> set default dns domain for all charts

- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/Chart.yaml
- charts/victoria-metrics-common/templates/_helpers.tpl
made name truncation optional. can be useful for fluxcd [variable substitution](https://fluxcd.io/flux/components/kustomize/kustomizations/#post-build-variable-substitution)
> common: added flag to disable name truncation

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/Chart.yaml
- charts/victoria-logs-single/files/dashboards/generated/victorialogs.yaml
- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/Chart.yaml
- charts/victoria-metrics-common/templates/_helpers.tpl
- charts/victoria-metrics-common/templates/_service.tpl
- charts/victoria-metrics-distributed/templates/extra-vmagent.yaml
- charts/victoria-metrics-distributed/templates/grafana-datasource.yaml
- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
- charts/victoria-metrics-k8s-stack/templates/rules/rule.yaml
- remove training slash in `vm.url` template. related issue https://github.com/VictoriaMetrics/helm-charts/issues/1706
- updated victorialogs grafana dashboard. fixes https://github.com/VictoriaMetrics/helm-charts/issues/1699
- allow disabling recording rules using `defaultRules.rules.<ruleName>.create: false`
> common: remove trailing slash from generated url

- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/Chart.yaml
- charts/victoria-metrics-common/templates/_helpers.tpl
- charts/victoria-metrics-distributed/templates/extra-vmagent.yaml
- charts/victoria-metrics-distributed/templates/grafana-datasource.yaml
- charts/victoria-metrics-distributed/templates/per-az/vmagent.yaml
- charts/victoria-metrics-distributed/templates/per-az/vmauth-read-proxy.yaml
- charts/victoria-metrics-distributed/templates/vmauth-read.yaml
- removed `global.name` and `global.<chart.name>.name` as sources of fullname prefix from `vm.fullname` template. it was required for victoria-logs-single chart before
- added `.alias` argument instead of doing `.prefix` magic
> common: removed unused fullname cases

- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-agent/templates/hpa.yaml
- charts/victoria-metrics-agent/templates/statefulset.yaml
- charts/victoria-metrics-alert/Chart.yaml
new vmalert and vmagent chart releases, fixed `.Values.statefulSet` variable name in templates
> vmagent: fixed statefulset variable name typo, new releases for vmalert and vmagent

- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/Chart.yaml
- charts/victoria-metrics-common/templates/_helpers.tpl
release 0.0.24 breaks adding suffix for names, that are using `vm.plain.fullname` template
> common: fixed vm.plain.fullname suffix

- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/templates/cleanup.yaml
- charts/victoria-metrics-operator/templates/crb.yaml
- charts/victoria-metrics-operator/templates/role.yaml
- charts/victoria-metrics-operator/templates/service_account.yaml
disable cleanup hook, when crds.enabled: false. related issue https://github.com/VictoriaMetrics/helm-charts/issues/1563, alternatively we can set `victoria-metrics-operator.crds.enabled: false` in k8s-stack chart by default
> operator: disable cleanup, when crds.enabled: false

- .gitignore
- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/Chart.yaml
- charts/victoria-metrics-common/templates/_helpers.tpl
- test-charts/victoria-metrics-common/Chart.lock
- test-charts/victoria-metrics-common/tests/helpers_test.yaml
allow looking for component data not only in `.Values` but also in `.`. Useful for distributed chart to allow defining a single template for all availability zones
> common: find app key in a context root

- charts/victoria-metrics-alert/values.yaml
Neither of the included parameters change the current behavior so no breaking changes.
Reason to add "rule" flag:
this is already set and since almost every user would need to modify this path. So including the flag in the values.yaml is very convenient.
Reason to add subPath:
Consistency with other sections. Conveniently showing how to mount the volume as a file instead of a directory.
> Added default flag "rule" and commented subPath 

- charts/victoria-metrics-alert/templates/server-deployment.yaml
The current template does not render extra volumes properly with the given values
here is the section for values.yaml
```yaml
extraVolumes:
- name: network-alerts
configMap:
name: network-alerts
extraVolumeMounts:
- name: network-alerts
mountPath: /rules/network-rules.yaml
subPath: network-rules.yaml
```
here is the rendered manifest in the previous template:
```yaml
volumeMounts:
- name: alerts-config
mountPath: /config
- mountPath: /config/network-rules.yaml
name: network-rules
volumes:
- name: alerts-config
configMap:
name: vmalert-stage-victoria-metrics-alert-server-alert-rules-config
- configMap:
- name: network-rules.yaml
name: network-rules
```
here is the rendered version in the corrected template:
```yaml
- name: network-rules
mountPath: /config/network-rules.yaml
subPath: …
```
> Fixed issue with deployment template

- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/Chart.yaml
- charts/victoria-metrics-common/templates/_helpers.tpl
common: removed `@sha` prefixed part from app version label value
related issue https://github.com/VictoriaMetrics/helm-charts/issues/1801
> common: trim app version label suffix

- .github/labeler.yaml
- charts/victoria-metrics-alert/templates/alertmanager-ingress.yaml
- charts/victoria-metrics-alert/templates/alertmanager-service.yaml
- charts/victoria-metrics-alert/values.yaml
This PR introduces the following improvements to the victoria-metrics-alert Helm chart:
* Improved context dictionary in alertmanager-ingress.yaml:
Added the appKey field to the context ($ctx) with the value alertmanager, enhancing the context for templating.
* Dynamic port assignment in alertmanager-service.yaml: Replaced the hardcoded port 9093 with a dynamic value using {{ $service.servicePort }}, allowing for better customization via Helm values.
These changes improve the configurability and flexibility of the Helm chart.
>  Fix Alertmanager Templates: Dynamic Port and Context Updates

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/README.md
- charts/victoria-logs-single/templates/vector.yaml
- charts/victoria-logs-single/values.yaml
@Haleygo 
this can be useful to support multiple vlogs installations where only single one has vector enabled
> vlogs: create vector config in a given namespace even if vector.enabled: false

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/README.md
- charts/victoria-logs-single/templates/_helpers.tpl
- charts/victoria-logs-single/values.yaml
server.retentionDiskUsage accepts both string and integer data, appends `GiB` to integer values
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1845
> vlogs: added option for retention by disk usage

- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/README.md.gotmpl
related issues https://github.com/VictoriaMetrics/helm-charts/issues/1563 and https://github.com/VictoriaMetrics/helm-charts/issues/1841
> k8s-stack: added note about installing operator separately

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboard.yaml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1851
> k8s-stack: allow manage default dashboards independently

- charts/victoria-metrics-k8s-stack/values.yaml
Noticed a tiny spelling error about grafanaOperator requirement in the `values.yaml` of victoria-metrics-k8s-stack :)
> chore(victoria-metrics-k8s-stack): Just a tiny spelling fix in the comment about grafanaOperator

- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/README.md.gotmpl
- charts/victoria-metrics-operator/templates/deployment.yaml
- charts/victoria-metrics-operator/templates/service_account.yaml
- charts/victoria-metrics-operator/values.yaml
Added an option to disable automatic token mount in order to avoid issues with security hardening.
> charts/operator: allow disabling automatic token mount

- charts/victoria-metrics-alert/templates/server-deployment.yaml
- charts/victoria-metrics-alert/templates/server-ingress.yaml
- charts/victoria-metrics-alert/templates/server-service.yaml
- charts/victoria-metrics-alert/values.yaml
Hi,
Since no one would be using this chart if they did not want the vm-alert server, having this condition is not required.
Cheers
> Omitted server-enabled

- charts/victoria-metrics-alert/Chart.yaml
- charts/victoria-metrics-alert/values.yaml
Updated the image for alert manager from 25 to 27
[alert-manager-chart](https://github.com/prometheus-community/helm-charts/blob/main/charts/alertmanager/Chart.yaml)
> Changed prom alertmanager image

- Makefile
- charts/victoria-logs-single/README.md
- charts/victoria-metrics-agent/README.md
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-anomaly/README.md
- charts/victoria-metrics-auth/README.md
- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-common/README.md
- charts/victoria-metrics-distributed/README.md
- charts/victoria-metrics-gateway/README.md
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-operator/README.md
- charts/victoria-metrics-single/README.md
- hack/docs/template.tmpl
* replace PWD with REPODIR in Makefile to fix run on PyCharm remote WSL2
> Fix values rendering for Markdown engines with strict XML parsing

- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/values.yaml
The following rules were missing in the values:
* `k8sContainerCpuLimits`
* `k8sContainerCpuRequests`
* `k8sContainerMemoryLimits`
* `k8sContainerMemoryRequests`
> add missing rule config in values.yaml

- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/README.md.gotmpl
- charts/victoria-metrics-operator/templates/deployment.yaml
- charts/victoria-metrics-operator/values.yaml
- Add an option to enable hostNetwork on operator deployment to work with custom CNI on managed Kubernetes clusters such as EKS.
> charts/operator: Add option to enable hostNetwork for custom CNI deployments

- charts/victoria-logs-single/templates/extra-objects.yaml
- charts/victoria-metrics-agent/templates/extra-objects.yaml
- charts/victoria-metrics-alert/templates/extra-objects.yaml
- charts/victoria-metrics-auth/templates/extra-objects.yaml
- charts/victoria-metrics-cluster/templates/extra-objects.yaml
- charts/victoria-metrics-k8s-stack/templates/extra-objects.yaml
- charts/victoria-metrics-operator/templates/extra-objects.yaml
- charts/victoria-metrics-single/templates/extra-objects.yaml
Currently, `extraObjects` only allows YAML inputs, which make it a pain to use templating within them. You can single quote a templated line for most cases, but this doesn't work with multiline things, such as labels.
Example:
```yaml
labels: {{ include "vm.labels" (dict "helm" . "appKey" "server" "extraLabels" .Values.server.service.labels) | nindent 4 }}
```
will template as
```yaml
labels: '
name: abc
label2: value'
```
As shown [in this documentation](https://docs.nautobot.com/projects/helm-charts/en/stable/advanced-features/extra-objects/), being able to pass the whole object as a string is great for templating and allows for these multiline strings.
> Add support for string extraObjects

- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-cluster/tests/__snapshot__/vmauth_test.yaml.snap
- charts/victoria-metrics-cluster/tests/__snapshot__/vminsert_test.yaml.snap
- charts/victoria-metrics-cluster/tests/__snapshot__/vmselect_test.yaml.snap
- charts/victoria-metrics-cluster/tests/__snapshot__/vmstorage_test.yaml.snap
- charts/victoria-metrics-cluster/values.yaml
- Remove vmstorage liveness probe, as vminsert already handles routing and retries, while liveness probes can inadvertently introduce delays, DNS instability, and unnecessary disruptions.
- Reduce the default readiness probe interval to 5s (was 15s) and the failure threshold to 10 (was 3).
- Add a default minReadySeconds for vmstorage, to help stabilizing service during rollout.
> vmcluster: improve components readiness check

- .github/workflows/release.yaml
The [latest release](https://github.com/VictoriaMetrics/helm-charts/actions/runs/12687268684/job/35361372478) failed when trying to create pull request:
```
aborted: you must first push the current branch to a remote, or use the --head flag
```
It's a [known issue](https://github.com/cli/cli/issues/6485#issuecomment-2560935183) with workaround, but I don't see a fix.
> fix release ci

- charts/victoria-metrics-distributed/Chart.yaml
- charts/victoria-metrics-distributed/templates/per-az/vmagent.yaml
- Fix typo `useMultitenantMode` -> `useMultiTenantMode` in remotewrite settings 
https://docs.victoriametrics.com/operator/api/#vmagentremotewritesettings
- Allow passing additional remotewrite setings
> victoria-metrics-distributed: fix typo

- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/Chart.yaml
- charts/victoria-metrics-common/templates/_pod.tpl
- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
- charts/victoria-metrics-k8s-stack/templates/grafana/datasource.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/values.yaml
- operator chart has `securityContext.enabled: true`, but it has no impact as it has no security context defined. adding default one. fixes https://github.com/VictoriaMetrics/helm-charts/issues/1960
- adding GrafanaDatasource support as an alternative to configMap. fixes https://github.com/VictoriaMetrics/helm-charts/issues/1964
- fixed minor issue in vm.securityContext common template
> operator: added default security context

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/vmalertmanager.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
Disabled by default as it requires migration for existing setups
Fixes #1968
> k8s-stack: added ability to use VMAlertmanagerConfig instead of plain k8s Secret. 

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/README.md
- charts/victoria-logs-single/templates/server-service.yaml
- charts/victoria-logs-single/values.yaml
- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/README.md
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-cluster/templates/service.yaml
- charts/victoria-metrics-cluster/templates/vmauth-deployment.yaml
- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-cluster/tests/__snapshot__/service_test.yaml.snap
- charts/victoria-metrics-cluster/values.yaml
- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/Chart.yaml
- charts/victoria-metrics-common/README.md
- charts/victoria-metrics-common/templates/_image.tpl
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/README.md
- charts/victoria-metrics-single/templates/server-service.yaml
- charts/victoria-metrics-single/values.yaml
https://github.com/VictoriaMetrics/helm-charts/issues/1938
> added ability to override default headless service

- charts/victoria-metrics-operator/templates/cleanup.yaml
`.Values.global.imagePullSecrets` is ignored during cleanup hook creation, causing issue when fetching image from private registry + using global value
Fixes #2002
> charts/operator: fix cleanup hook does not use global imagePullSecrets

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/Chart.yaml
- charts/victoria-logs-single/templates/server-service.yaml
`.Values.server.service.enabled` option does not exist, so the check is always failing. This leads to service being deleted after the upgrade.
> charts/victoria-logs-single: fix service not being rendered

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/Chart.yaml
- charts/victoria-logs-single/templates/server.yaml
- charts/victoria-logs-single/tests/__snapshot__/server_test.yaml.snap
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/Chart.yaml
- charts/victoria-metrics-single/templates/server.yaml
serviceName removal makes smooth upgrade impossible and requires statefulset recreation. reverting it back
> single: revert serviceName removal from statefulSet mode

- charts/victoria-metrics-k8s-stack/templates/ingress.yaml
Annotations templating can be useful to template some variables like cluster name in some controller used annotation like externalDns
> feat: Add posibility to template ingress annotations

- charts/victoria-metrics-k8s-stack/values.yaml
erofs should be considered as squashfs, a read only file system that should not be monitored
> Add erofs to ignored fs type

- charts/victoria-metrics-k8s-stack/Chart.yaml
This will upgrade the [node-exporter docker image](quay.io/prometheus/node-exporter) to the latest available v1.9.1 (as of date)
> [k8s-stack] chore(deps): upgrade node-exporter chart to v4.45.x

- charts/victoria-metrics-distributed/CHANGELOG.md
- charts/victoria-metrics-distributed/tests/__snapshot__/vmauth_test.yaml.snap
- charts/victoria-metrics-distributed/values.yaml
Before, the read path will fail when the first zone vmselect is down, since zone vmauth will return [error code 502](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/89237a04b9de5f04957e71287a229ffe2aac9d54/app/vmauth/main.go#L288-L291)
```
< HTTP/1.1 502 Bad Gateway
remoteAddr: "10.244.2.15:40940, X-Forwarded-For: 127.0.0.1"; requestURI: /select/0; all the 2 backends for the user "" are unavailable
```
In this pull request, expand retry status codes for both global and cross-zone vmauth, to cover more cases.
> distributed: fix read vmauth retry status codes

- .github/ci/ct.yaml
Fixes `make lint-ct` configuration reference to chart schema file.
> make: fix reference to config file

- charts/victoria-logs-cluster/CHANGELOG.md
- charts/victoria-logs-cluster/Chart.yaml
- charts/victoria-logs-cluster/README.md
- charts/victoria-logs-cluster/tests/__snapshot__/hpa_test.yaml.snap
- charts/victoria-logs-cluster/tests/__snapshot__/vlinsert_test.yaml.snap
- charts/victoria-logs-cluster/values.yaml
- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/Chart.yaml
- charts/victoria-logs-single/README.md
- Disable vlinsert HPA by default.
- Bump VictoriaLogs version to [v1.21.0]
> vlogs charts: upgrade version and minor fix

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/datasource.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
Fixed the following error:
> Error: UPGRADE FAILED: release vmks failed, and has been rolled back due to atomic being set: cannot patch "vmks-victoria-metrics-k8s-stack-victoriametrics-ds" with kind GrafanaDatasource: GrafanaDatasource.grafana.integreatly.org "vmks-victoria-metrics-k8s-stack-victoriametrics-ds" is invalid: [spec.plugins[0]: Invalid value: "string": spec.plugins[0] in body must be of type object: "string", <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation]
[Grafana Operator API Reference - GrafanaDashboard.spec.plugins[index]](https://grafana.github.io/grafana-operator/docs/api/#grafanadashboardspecpluginsindex)
Related Issue: #2168
Related Commit: …
> k8s-stack: fix plugins section in GrafanaDatasource

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
fba36ed incorrectly changed order of merge for vmagent spec which resulted in global `$spec` taking over `$Values.vmagent.spec`. As the result `spec` from previous component would override vmagent config. For example, tag would be set to `v1.118.0-enterprise-cluster` with the following config;
```yaml
vmcluster:
...
spec:
clusterVersion: "v1.118.0-enterprise-cluster"
...
vminsert:
image:
tag: v1.118.0-enterprise-cluster
vmstorage:
image:
tag: v1.118.0-enterprise-cluster
vmselect:
image:
tag: v1.118.0-enterprise-cluster
```
> charts/victoria-metrics-k8s-stack: fix templating of image.tag for vmagent

- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-agent/templates/service.yaml
- charts/victoria-metrics-agent/values.yaml
Based on https://kubernetes.io/docs/concepts/services-networking/service/#traffic-distribution
Minimum Kubernetes needed is v1.31, but full functionality can be achieved in Kubernetes v1.33
> charts/vmagent: Add trafficDistribution for service in vmagent chart

- charts/victoria-metrics-operator/templates/role.yaml
See
https://docs.victoriametrics.com/operator/changelog/#v0610
> Update Note 2:: This release requires an additional pods/eviction RBAC permssion for operator.
https://github.com/VictoriaMetrics/operator/commit/4af4a5b5712e6a4c0d105575d7180d53c5c8aa49
> Missing RBAC permission for 0.61 update to Victoria-Metrics-Operator

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/templates/monitor.yaml
- charts/victoria-logs-single/values.yaml
victoria-logs-single lacks the method to add params to ServiceMonitor, this PR adds that support.
If the server is configured with:
```
server:
extraArgs:
metricsAuthKey: '<key>'
```
then the ServiceMonitor needs to add a param to scrape metrics.  The PR adds ServiceMonitor.parms as a template so that the authKey can be set from the provided parameter value (with a commented example added in values.yaml).
I didn't want to make the parameter included by default (in this case) in case someone wanted to set the value directly...(and would make for complex key checking in the template).
> charts/victoria-logs-single: add params to ServiceMonitor

- charts/victoria-logs-collector/CHANGELOG.md
- charts/victoria-logs-collector/Chart.yaml
- charts/victoria-logs-collector/templates/daemonset.yaml
Related: #2429 
The image will be smaller after these changes: 
`0.49.0-distroless-libc` image size: 229MB
`0.49.0-alpine` image size: 190MB
But there's a chance that performance may drop, since the alpine image is based on musl.
> charts/victoria-logs-collector: switch Vector to alpine-based build

- charts/victoria-logs-cluster/CHANGELOG.md
- charts/victoria-logs-cluster/templates/vmauth-server.yaml
This pull request introduces an improvement to the `vmauth-server.yaml` Helm template by adding a checksum annotation for the `vmauth-config.yaml` file. This ensures that changes to the config file trigger a rolling update of the deployment.
- **Helm template enhancements:**
* Added a `vmauth-sha256sum` annotation to the pod template metadata in `vmauth-server.yaml`, which computes and stores the SHA256 hash of the `vmauth-config.yaml` file. This helps Kubernetes detect changes in the config and automatically roll out new pods when the config changes.
> fix: Add vmauth-sha256sum annotation to vmauth-server template
