VictoriaMetrics/helm-charts

- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
- charts/victoria-metrics-cluster/templates/vminsert-ingress.yaml
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-ingress.yaml
https://github.com/VictoriaMetrics/helm-charts/issues/4
> fix: apiVersion of Deployment and Ingress object

- charts/victoria-metrics-single/values.yaml
existingClaim dont using, updating to storageClass
> existingClaim -> storageClass

- charts/victoria-metrics-single/Chart.yaml
- charts/victoria-metrics-single/templates/pdb.yaml
- charts/victoria-metrics-single/values.yaml
Signed-off-by: Sergey Monakhov <sergey.monakhov@gmail.com>
Added PodDisruptionBudget template to helm chart
> add PodDisruptionBudget

- charts/victoria-metrics-single/Chart.yaml
- charts/victoria-metrics-single/templates/server-service-monitor.yaml
Adding possibility of setting ServiceMonitor namespace also for single container version (see also #18 for cluster version).
> Namespace for ServiceMonitor

- charts/victoria-metrics-single/templates/server-pvc.yaml
Fixes #27 
Tested with: helm install --dry-run --debug
> Add PVC for deployment mode

- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-agent/templates/deployment.yaml
- charts/victoria-metrics-agent/values.yaml
added annotations and podAnnotations in helm chart vmagent
> added annotations and podAnnotations in helm chart vmagent

- charts/victoria-metrics-alert/Chart.yaml
- charts/victoria-metrics-alert/templates/server-deployment.yaml
> vmalert - change remote naming

- charts/victoria-metrics-alert/Chart.yaml
- charts/victoria-metrics-alert/templates/server-deployment.yaml
- Restart pods when configmap updates
- bump vmalert chart version
> Automatically roll vmalert deployment

- charts/victoria-metrics-agent/templates/deployment.yaml
- charts/victoria-metrics-agent/values.yaml
"/" may not be writable in restricted containers
> Change working dir to /tmp in vmagent chart

- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-agent/templates/clusterrole.yaml
- charts/victoria-metrics-agent/templates/clusterrolebinding.yaml
- charts/victoria-metrics-agent/templates/podsecuritypolicy.yaml
- charts/victoria-metrics-agent/values.yaml
- charts/victoria-metrics-alert/Chart.yaml
- charts/victoria-metrics-alert/templates/clusterrolebinding.yaml
- charts/victoria-metrics-alert/templates/podsecuritypolicy.yaml
- charts/victoria-metrics-alert/templates/role.yaml
- charts/victoria-metrics-alert/templates/rolebinding.yaml
- charts/victoria-metrics-alert/values.yaml
agent:
add psp definitions
add extralabel support to clusterole and its binding
alert:
add clusterrole, role and binding
add psp definitions
addresses #42
> Add psp support for agent and alert

- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
> Fix label error

- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/templates/extra-secrets.yaml
- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-cluster/values.yaml
- charts/victoria-metrics-single/templates/server-deployment.yaml
- charts/victoria-metrics-single/templates/server-statefulset.yaml
- charts/victoria-metrics-single/values.yaml
This changes are useful for backup/restore processes. Extra secret are used to provide s3 credentials for vmrestore(for ex.). Init containers are also may be used to restore VM from backup.
> added extrasecret and initcontainers

- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-agent/templates/_helpers.tpl
- charts/victoria-metrics-agent/templates/deployment.yaml
- charts/victoria-metrics-agent/templates/service.yaml
- charts/victoria-metrics-agent/templates/statefulset.yaml
- charts/victoria-metrics-agent/values.yaml
Added the ability to add ports for all ingestion protocols in vmagent
> Add ports for all ingestion protocols to vmagent

- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/templates/alertmanager-ingress.yaml
- charts/victoria-metrics-alert/values.yaml
Added ingress template for alertmanager
> Alertmanager ingress

- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/ingress.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/monzo-template.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/vmalertmanager.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
- Added ingress for alertmanager instance
- Cleaned up a bit Spec generation for alertmanager
- Added fancy alert templates from https://gist.github.com/milesbxf/e2744fc90e9c41b47aa47925f8ff6512
it changes this 
to this
> added alertmanager ingress and monzo alert template

- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/uninstall_hook.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
https://github.com/VictoriaMetrics/helm-charts/issues/131
> adds cleanup job for operator resources

- charts/victoria-metrics-k8s-stack/Chart.lock
- charts/victoria-metrics-k8s-stack/Chart.yaml
bump dependendies to actual version
change depracated kube-state-metrics to actual from prometheus-community
> bump dependendies to actual version

- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/README.md.gotmpl
Since #136 this repo is not used
> Remove unused dependency from README

- charts/victoria-metrics-k8s-stack/templates/servicemonitors/kube-controller-manager.yaml
- charts/victoria-metrics-k8s-stack/templates/servicemonitors/kube-proxy.yaml
add missed servicemonitor for kube-controller-manager
fixed k8s-app name in kube-proxy scrape
> add missed servicemonitor for kube-controller-manager

- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/values.yaml
- charts/victoria-metrics-operator/README.md
- charts/victoria-metrics-operator/templates/deployment.yaml
- charts/victoria-metrics-operator/values.yaml
fix spelling for pull request
https://github.com/VictoriaMetrics/helm-charts//133
закройте этот пулл реквест, и вмерджите этот без мердж-конфликтов, версию чарта поменять можно будет при влитии других изменений, с этой ошибкой чарт и так работает.
> fix spelling without merge conflict

- charts/victoria-metrics-k8s-stack/Chart.lock
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/ingress.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmagent.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmalert.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmsingle.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
update dependencies version to latest
add optional ingress for vmagent/vmalert/vmsingle
change alertmanager ingress temlate
> add optional ingress for vmagent/vmalert/vmsingle

- charts/victoria-metrics-k8s-stack/templates/rules/serviceHealth.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
> changes kubectl image

- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-agent/templates/_helpers.tpl
- charts/victoria-metrics-agent/templates/statefulset.yaml
- charts/victoria-metrics-single/Chart.yaml
- charts/victoria-metrics-single/templates/_helpers.tpl
- charts/victoria-metrics-single/templates/scrape-configmap.yaml
- charts/victoria-metrics-single/templates/server-deployment.yaml
- charts/victoria-metrics-single/templates/server-statefulset.yaml
- charts/victoria-metrics-single/values.yaml
single node
- add scrape config
- add containerWorkingDir
vmagent
- fix template
- fix typos
> Add scrape config to single-node

- charts/victoria-metrics-k8s-stack/hack/sync_grafana_dashboards.py
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/etcd.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-coredns.yaml
add grafana dashboard for etcd and coredns
> add grafana dashboard for etcd and coredns

- charts/victoria-metrics-k8s-stack/Chart.lock
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/hack/sync_grafana_dashboards.py
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/etcd.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-coredns.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-resources-cluster.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-resources-namespace.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-resources-pod.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/kubelet.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/nodes.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/persistentvolumesusage.yaml
- charts/victoria-metrics-k8s-stack/templates/rules/kube-apiserver-availability.rules.yaml
- charts/victoria-metrics-k8s-stack/templates/rules/kube-apiserver.rules.yaml
- charts/victoria-metrics-k8s-stack/templates/rules/kube-state-metrics.yaml
- charts/victoria-metrics-k8s-stack/templates/rules/serviceHealth.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
* removed external label `cluster` for vmalert to fix multi cluster setup
* updated grafana dashboards
* added coredns and etcd. thanks to @kevinvirs #147 
* updated rules from upstream
* updated dependencies
> Fix vmalert relabel, update deps

- charts/victoria-metrics-k8s-stack/hack/sync_grafana_dashboards.py
remove doubles
{
'source': 'https://etcd.io/docs/v3.4/op-guide/grafana.json',
'destination': '../templates/grafana/dashboards',
'type': 'json'
},
> remove doubles

- charts/victoria-metrics-k8s-stack/Chart.lock
- charts/victoria-metrics-k8s-stack/Chart.yaml
> update grafana and kube-state-metrics

- charts/victoria-metrics-k8s-stack/templates/grafana/datasource.yaml
just disable single datasource. in case single is disabled.
> in case single is disabled

- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
- charts/victoria-metrics-cluster/templates/vminsert-hpa.yaml
- charts/victoria-metrics-cluster/values.yaml
same as https://github.com/VictoriaMetrics/helm-charts/pull/172 just for the vminsert component.
> Add HPA Support to vminsert component

- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/hack/sync_grafana_dashboards.py
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/clusterbytenant.yaml
small hotfix, right now installation is broken (
> fix: condition type for cluster dashboard

- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-agent/templates/deployment.yaml
- charts/victoria-metrics-agent/templates/statefulset.yaml
- charts/victoria-metrics-agent/values.yaml
Adds support for the VMAgent multitenantURL PR https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1505
> Support Agent remoteWrite.multitenantURL

- charts/victoria-metrics-k8s-stack/Chart.lock
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/node-cluster-rsrc-use.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/node-rsrc-use.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/nodes.yaml
- charts/victoria-metrics-k8s-stack/templates/rules/k8s.rules.yaml
- charts/victoria-metrics-k8s-stack/templates/rules/vm-health.yaml
- charts/victoria-metrics-k8s-stack/templates/rules/vmsingle.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/monzo-template.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
so now out of the box we can create alerts with label `code_owner_channel` and they will be routed to appropriate channel.
of course most users have their own routing configuration, but this is nice to have out of the box, and also can be an inspiration for users =)
also updated dependencies =)
> Codeowner rule fix

- .github/.workflow/labeler.yaml
- .github/labeler.yaml
small improvement to automatically label incoming PRs
> added autolabeling action

- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/templates/alertmanager-ingress.yaml
- charts/victoria-metrics-alert/templates/server-ingress.yaml
- charts/victoria-metrics-alert/values.yaml
for using in ingress added alertmanager's service. also fixed wrong variable path in alertmanager-ingress
> add alertmanager service, fixed var in ingress

- charts/victoria-metrics-single/templates/server-statefulset.yaml
Similar to [#188](https://github.com/VictoriaMetrics/helm-charts/pull/188)  for single node chart
> Fix server.persistentVolume.existingClaim

- .github/labeler.yaml
i hope this is last change=)
sorry i don't know how i missed it
> labeler root path fix

- .github/CODEOWNERS
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
> adds code owners

- charts/victoria-metrics-agent/README.md
- charts/victoria-metrics-agent/templates/service-monitor.yaml
- charts/victoria-metrics-alert/Chart.yaml
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/templates/service-monitor.yaml
https://github.com/VictoriaMetrics/helm-charts/issues/200
> minor fixes to agent and alert service monitors

- charts/victoria-metrics-agent/values.yaml
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/values.yaml
- charts/victoria-metrics-auth/values.yaml
- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-cluster/values.yaml
- charts/victoria-metrics-single/README.md
- charts/victoria-metrics-single/values.yaml
related issue https://github.com/VictoriaMetrics/helm-charts/issues/230
> Add info how to set flags via env in readme.md (#230)

- charts/victoria-metrics-operator/README.md
- charts/victoria-metrics-operator/templates/deployment.yaml
- charts/victoria-metrics-operator/values.yaml
this PR will make it possible to configure per Pods labels for Operator
> added podLabels value

- charts/victoria-metrics-k8s-stack/hack/sync_grafana_dashboards.py
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/alertmanager-overview.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/apiserver.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/cluster-total.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/controller-manager.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/etcd.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-coredns.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-resources-cluster.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-resources-namespace.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-resources-node.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-resources-pod.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-resources-workload.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-resources-workloads-namespace.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/kubelet.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/namespace-by-pod.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/namespace-by-workload.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/node-cluster-rsrc-use.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/node-rsrc-use.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/nodes.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/persistentvolumesusage.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/pod-total.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/proxy.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/scheduler.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/statefulset.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/victoriametrics-cluster.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/victoriametrics.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/vmagent.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/vmalert.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/workload-total.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
Add additional labels and annotations for victoriametrics dashboards
Example usage:
```
dashboards:
additionalDashboardLabels:
"some_key": "some_label_value"
additionalDashboardAnnotations:
"some_key": "some_annotation_value"
```
> Add additional labels and annotations for victoriametrics dashboards

- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-alert/Chart.yaml
- charts/victoria-metrics-auth/Chart.yaml
- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-gateway/Chart.yaml
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-operator/Chart.yaml
- charts/victoria-metrics-single/Chart.yaml
This way it adds clickable URLs in sources section per chart, thus
it is easier to find chart source.
> chore: update sources in the charts

- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
Signed-off-by: Artem Navoiev <tenmozes@gmail.com>
> Prettify vminsert template

- charts/victoria-metrics-operator/Chart.yaml
Looks like you forgot to update appVersion in `victoria-metrics-operator` helm chart
> update operator appVersion

- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/_rules.tpl
Not much to add beyond the title. 😄
> Fix a likely typo in the alertmanager line

- charts/victoria-metrics-k8s-stack/values.yaml
> bump up gcr.io/google_containers/hyperkube

- charts/victoria-metrics-k8s-stack/Chart.yaml
this PR fix https://github.com/VictoriaMetrics/operator/issues/529
> fix: bump victoria-metrics-operator's version to 0.15.*

- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-resources-cluster.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-resources-namespace.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-resources-pod.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/kubelet.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/node-cluster-rsrc-use.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/nodes-darwin.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/nodes.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/victoriametrics-cluster.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/victoriametrics.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/vmagent.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/vmalert.yaml
As rules were updated it makes sense to update dashboards as well, to reflect changes in series analysis.
> [victoria-metrics-k8s-stack]: Update dashboards as well, to match changes in rules

- Makefile
- charts/victoria-metrics-agent/templates/pdb.yaml
- charts/victoria-metrics-alert/templates/server-pdb.yaml
- charts/victoria-metrics-auth/templates/pdb.yaml
- charts/victoria-metrics-cluster/templates/vminsert-pdb.yaml
- charts/victoria-metrics-cluster/templates/vmselect-pdb.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-pdb.yaml
- charts/victoria-metrics-gateway/templates/pdb.yaml
- charts/victoria-metrics-single/templates/pdb.yaml
- hack/vmagent-lint-hack.yaml
- hack/vmalert-lint-hack.yaml
- hack/vmauth-lint-hack.yaml
- hack/vmcluster-template-hack.yaml
- hack/vmgateway-cluster-ratelimiting-minimum.yaml
- hack/vmsingle-lint-hack.yaml
- Fix spacing
- Add template job for make to test charts
- Configure all charts to use PDB during lint/template
> fix: fix spacing for PDB resources in charts

- charts/victoria-metrics-single/templates/_helpers.tpl
Should use .Values.server.scrape.configMap instead of .Values.configMap
> Fix configMap value in helpers

- .github/workflows/run-lint.yaml
- Makefile
This should help to catch issues which can be hard to notice manually
> ci: setup lint and template runs

- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/values.yaml
Signed-off-by: Artem Navoiev <tenmozes@gmail.com>
> followup after fbb3104ef5755750e5cecfc9153f3bf8ccb26ca1

- charts/victoria-metrics-k8s-stack/.helmignore
Solves https://github.com/VictoriaMetrics/helm-charts/issues/424
> Add img/ to .helmignore to avoid helm 1048576 limit.

- .github/ci/chart_schema.yaml
- .github/ci/ct.yaml
- .github/ci/lintconf.yaml
- .github/workflows/run-testing.yaml
- Makefile
- hack/helm/victoria-metrics-agent.yaml
- hack/helm/victoria-metrics-alert.yaml
- hack/helm/victoria-metrics-anomaly.yaml
- hack/helm/victoria-metrics-auth.yaml
- hack/helm/victoria-metrics-cluster.yaml
- hack/helm/victoria-metrics-gateway.yaml
- hack/helm/victoria-metrics-single.yaml
This PR adds a workflow which will run install command and verify that deployment will be successful for the given chart.
Workflow is using dynamically built matrix to validate only changed charts.
Here are several run examples:
- https://github.com/VictoriaMetrics/helm-charts/actions/runs/3658586426 - single changed chart
- https://github.com/VictoriaMetrics/helm-charts/actions/runs/3658372967 - all charts "fake" changed
> ci: configure chart installation for testing

- charts/victoria-metrics-agent/README.md
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-anomaly/Chart.yaml
- charts/victoria-metrics-anomaly/README.md
- charts/victoria-metrics-anomaly/templates/configmap.yaml
- charts/victoria-metrics-anomaly/templates/deployment.yaml
- charts/victoria-metrics-anomaly/values.yaml
- charts/victoria-metrics-auth/README.md
- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-gateway/README.md
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-single/README.md
Signed-off-by: Artem Navoiev <tenmozes@gmail.com>
> reflect 1.0.0 breaking chnages in vmanomlay helm chart

- charts/victoria-metrics-cluster/values.yaml
Indentation of values is one off.
> fix indentation in values file of cluster chart

- charts/victoria-metrics-anomaly/Chart.yaml
- charts/victoria-metrics-anomaly/templates/configmap.yaml
indent fix for vmanomaly config
> vmanomaly: fix monitoring part of config

- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/README.md.gotmpl
- charts/victoria-metrics-k8s-stack/values.yaml
Hello,
Just a small PR to fix link to the documentation of CRD
Best
> docs: avoid redirect and loose anchor

- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
> Change local vmagent remote write port to 8429

- charts/victoria-metrics-k8s-stack/Chart.yaml
fix https://github.com/VictoriaMetrics/helm-charts/issues/533
> [victoriametrics-k8s-stack] Upgrade dependency victoria-metrics-operator

- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-operator/README.md
- charts/victoria-metrics-operator/templates/pdb.yaml
- charts/victoria-metrics-operator/values.yaml
Allows to set a podDisruptionBudget on operator pods
> feat(operator): add PodDisruptionBudget

- charts/victoria-metrics-cluster/templates/_helpers.tpl
- charts/victoria-metrics-single/templates/_helpers.tpl
- use same securityPolicy defined for vmstorage
- fix indentation levels for env and resources blocks
> charts/cluster: fix vmbackupmanager init container configurationtion

- Makefile
Should address https://github.com/VictoriaMetrics/helm-charts/issues/547
> package only chart which changes the version

- charts/victoria-metrics-anomaly/Chart.yaml
- charts/victoria-metrics-anomaly/templates/configmap.yaml
- charts/victoria-metrics-anomaly/values.yaml
Made them more realistic:
- Bump version to 0.3.2
- Change defaults
- Add samplingPeriod param
> Anomaly: change defaults

- charts/victoria-metrics-cluster/values.yaml
> Fix typo storage pods

- .github/ci/ct.yaml
- charts/victoria-logs-single/Chart.lock
- charts/victoria-logs-single/Chart.yaml
- charts/victoria-logs-single/README.md
- charts/victoria-logs-single/README.md.gotmpl
- charts/victoria-logs-single/values.yaml
Added fluentbit configuration to collect logs from pods in cluster, disabled by default.
> charts/victoria-logs-single: add fluentbit setup

- .github/ci/helm-repos.yaml
- Makefile
Lint task was failing in case deps where not built manually before running. Added repos configuration and task to run `dep build` for this chart before running lint and template.
> ci: fix linting for vlogs-single

- charts/victoria-metrics-single/README.md
- charts/victoria-metrics-single/templates/extra-objects.yaml
- charts/victoria-metrics-single/values.yaml
Same as PR:
- #558
but for vmsingle :-)
> feat(vmsingle): Add ability to deploy extra manifests

- charts/victoria-logs-single/README.md
> charts/victoria-logs-single: add imagePullSecrets

- charts/victoria-logs-single/values.yaml
Follow-up for https://github.com/VictoriaMetrics/helm-charts/pull/592 to reflect swapped fields.
> vlogs-single: fix podSecurityContext and securityContext usage

- charts/victoria-metrics-k8s-stack/values.yaml
see https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack#upgrade-to-0130
> delete an obsolete parameter remaining by mistake 

- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-single/CHANGELOG.md
Make up changelog for https://github.com/VictoriaMetrics/helm-charts/pull/617
> make up changelog for #617

- charts/victoria-metrics-k8s-stack/hack/sync_grafana_dashboards.py
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/alertmanager-overview.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/backupmanager.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/grafana-overview.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-system-coredns.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-views-global.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-views-namespaces.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-views-pods.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/operator.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/victoriametrics-cluster.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/victoriametrics.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/vmagent.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/vmalert.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
This change allows to setup dashboards for grafana-operator
https://github.com/grafana-operator/grafana-operator
> Add support for grafna-operator dashboards

- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/README.md
- charts/victoria-metrics-agent/values.yaml
follow up https://github.com/VictoriaMetrics/helm-charts/pull/617
> victoria-metrics-agent: fix honor_timestamps field

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
> follow up after #619

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
add changelog for https://github.com/VictoriaMetrics/helm-charts/pull/636
> add changelog for https://github.com/VictoriaMetrics/helm-charts/pull/636

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.lock
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/charts/crds/crds/crd.yaml
> Bump version of operator helm-chart to `0.26.2` (and update CRD) in k8s-stack

- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-cluster/templates/vminsert-hpa.yaml
- charts/victoria-metrics-cluster/templates/vmselect-hpa.yaml
- charts/victoria-metrics-cluster/values.yaml
PR for https://github.com/VictoriaMetrics/helm-charts/issues/679
> feat: add behavior option to vminsert/vmselect HPA

- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/templates/extra-objects.yaml
- charts/victoria-metrics-alert/values.yaml
- charts/victoria-metrics-auth/CHANGELOG.md
- charts/victoria-metrics-auth/README.md
- charts/victoria-metrics-auth/templates/extra-objects.yaml
- charts/victoria-metrics-auth/values.yaml
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-cluster/templates/extra-objects.yaml
- charts/victoria-metrics-cluster/values.yaml
Sync supported options between different charts to make sure all charts support extraObjects.
> charts: add ability to provide extraObjects

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/Chart.yaml
- charts/victoria-logs-single/values.yaml
- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/Chart.yaml
- charts/victoria-metrics-auth/CHANGELOG.md
- charts/victoria-metrics-auth/Chart.yaml
- charts/victoria-metrics-auth/values.yaml
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/values.yaml
- charts/victoria-metrics-gateway/CHANGELOG.md
- charts/victoria-metrics-gateway/Chart.yaml
- charts/victoria-metrics-gateway/values.yaml
- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/Chart.yaml
- charts/victoria-metrics-operator/templates/crd.yaml
- charts/victoria-metrics-operator/values.yaml
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/Chart.yaml
- charts/victoria-metrics-single/values.yaml
- vm 1.94.0
- vmlogs 0.4.1
- operator 0.39.0
> Release new version of VM components

- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/Chart.yaml
- charts/victoria-metrics-operator/templates/role.yaml
follow up for #711 / #707
issue #708
> Added endpointslices permissions to operator roles (#708)

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.lock
- charts/victoria-metrics-k8s-stack/Chart.yaml
related links:
- #708 
- #710 
- #711 
- #713
> Update operator chart to v0.27.3 for fixing #708

- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/templates/_helpers.tpl
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/templates/_helpers.tpl
- charts/victoria-metrics-single/templates/server-deployment.yaml
- charts/victoria-metrics-single/templates/server-statefulset.yaml
- add license/eula enforcement when using vmbackupmanager
- fix missing license flags for vmsingle STS
> {single,cluster}: add license enforcement for vmbackupmanager

- charts/victoria-metrics-agent/values.yaml
- charts/victoria-metrics-single/values.yaml
fix https://github.com/VictoriaMetrics/helm-charts/issues/694
> fix comment about `insecure_skip_verify`

- charts/victoria-metrics-gateway/Chart.yaml
follow up https://github.com/VictoriaMetrics/helm-charts/commit/d89571027ed18d53f5d877998b9630e509833a58
> fix gateway chart version

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
- charts/victoria-metrics-anomaly/README.md
- charts/victoria-metrics-anomaly/templates/configmap.yaml
- charts/victoria-metrics-anomaly/values.yaml
- hack/vmanomaly-lint-hack.yaml
- add "bearer_token" parameter for read/write configs
- add "verify_tls" parameter for read/write configs
- add "extra_filters" parameter for read config
> vmanomaly: new version, reflect config updates

- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/Chart.yaml
- charts/victoria-metrics-operator/templates/crd.yaml
- charts/victoria-metrics-operator/values.yaml
bump version of VM operator to [0.39.1](https://github.com/VictoriaMe…trics/operator/releases/tag/v0.39.1)
> bump version of VM operator to 0.39.1

- charts/victoria-metrics-k8s-stack/values.yaml
kube state metrics helm chart is maintained by prometheus team
> kube state metrics helm chart is maintained by prometheus community

- charts/victoria-metrics-k8s-stack/templates/grafana/datasource.yaml
changing `defaultDatasourceType` doesn't change default datasource configuration
> fixed datasource template

- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/Chart.yaml
- charts/victoria-metrics-operator/crd.yaml
This is a follow-up for 6d1c95ec.
> victoria-metrics-operator: sync CRD resources with operator v0.39.3

- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-agent/templates/_helpers.tpl
- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/Chart.yaml
- charts/victoria-metrics-alert/templates/_helpers.tpl
- charts/victoria-metrics-auth/CHANGELOG.md
- charts/victoria-metrics-auth/Chart.yaml
- charts/victoria-metrics-auth/templates/_helpers.tpl
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/templates/_helpers.tpl
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-gateway/CHANGELOG.md
- charts/victoria-metrics-gateway/Chart.yaml
- charts/victoria-metrics-gateway/templates/_helpers.tpl
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/Chart.yaml
- charts/victoria-metrics-single/templates/_helpers.tpl
- fix reference of license by correct secret key
- fix flag name after rename in VictoriaMetrics
> license configuration: fix passing license via k8s secret

- charts/victoria-metrics-operator/templates/uninstall_hook.yaml
[[victoria-metrics-operator] add imagePullSecrets to imagePullSecrets
> [victoria-metrics-operator] add imagePullSecrets to imagePullSecrets:

- charts/victoria-metrics-agent/Chart.yaml
Bump chart version in order to release https://github.com/VictoriaMetrics/helm-charts/pull/806
> charts/victoria-metrics-agent: bump chart version for release

- charts/victoria-metrics-k8s-stack/values.yaml
> update job label to coredns

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
- charts/victoria-metrics-anomaly/values.yaml
- changes according to `vmanomaly` v1.10 multimodel config
- docs fixes
> Vmanomaly v1.10 changes

- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/Chart.yaml
- charts/victoria-metrics-operator/crd.yaml
- charts/victoria-metrics-operator/values.yaml
and also extended info in README about CRD update in k8s-stack
> prepare release for operator chart with version 0.41.2

- charts/victoria-metrics-alert/Chart.yaml
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/values.yaml
- update docs format
- bump chart version to release #871 changes
> charts/vmalert: follow-up for 01c5724e2b8da7282117b6232d4348882a0db69a

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
- charts/victoria-metrics-anomaly/README.md
- charts/victoria-metrics-anomaly/values.yaml
- multischeduler config changes
> Vmanomaly - v1.11 version modification

- charts/victoria-metrics-k8s-stack/values.yaml
Was working on the VM k8s stack and observed this typo.
> fix: typo on whether

- charts/victoria-logs-single/README.md
- charts/victoria-logs-single/templates/server-service-monitor.yaml
- charts/victoria-logs-single/values.yaml
- charts/victoria-metrics-agent/README.md
- charts/victoria-metrics-agent/templates/service-monitor.yaml
- charts/victoria-metrics-agent/values.yaml
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/templates/service-monitor.yaml
- charts/victoria-metrics-alert/values.yaml
- charts/victoria-metrics-auth/README.md
- charts/victoria-metrics-auth/templates/service-monitor.yaml
- charts/victoria-metrics-auth/values.yaml
- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-cluster/templates/vminsert-service-monitor.yaml
- charts/victoria-metrics-cluster/templates/vmselect-service-monitor.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-service-monitor.yaml
- charts/victoria-metrics-cluster/values.yaml
- charts/victoria-metrics-gateway/README.md
- charts/victoria-metrics-gateway/templates/service-monitor.yaml
- charts/victoria-metrics-gateway/values.yaml
- charts/victoria-metrics-single/README.md
- charts/victoria-metrics-single/templates/server-service-monitor.yaml
- charts/victoria-metrics-single/values.yaml
> Add `metricRelabelings` values to helm charts

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/Chart.yaml
- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/Chart.yaml
- charts/victoria-metrics-auth/CHANGELOG.md
- charts/victoria-metrics-auth/Chart.yaml
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-gateway/CHANGELOG.md
- charts/victoria-metrics-gateway/Chart.yaml
- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/Chart.yaml
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/Chart.yaml
follow up https://github.com/VictoriaMetrics/helm-charts/commit/538135fa3957403b883ebf943de9146e7c3efc0d
> prepare to relase

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
> vmanomaly: use v1.12 as a default

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/README.md.gotmpl
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-views-global.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-views-namespaces.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/victoriametrics-cluster.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/victoriametrics.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/vmagent.yaml
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/vmalert.yaml
- charts/victoria-metrics-k8s-stack/templates/rules/node-exporter.yaml
- charts/victoria-metrics-k8s-stack/templates/rules/vmcluster.yaml
- charts/victoria-metrics-k8s-stack/templates/rules/vmsingle.yaml
- charts/victoria-metrics-k8s-stack/values.minikube.yaml
upgraded dashboards and rules, added instructions about how to set up vmstack in minikube
> vmstack: dashboards and rules upgrade, added minikube setup instructions

- charts/victoria-metrics-cluster/templates/_helpers.tpl
> Labels should be truncated

- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-cluster/values.yaml
> introduce templating for container port name

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/Chart.yaml
- charts/victoria-logs-single/README.md
- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-agent/README.md
- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/Chart.yaml
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
- charts/victoria-metrics-anomaly/README.md
- charts/victoria-metrics-auth/CHANGELOG.md
- charts/victoria-metrics-auth/Chart.yaml
- charts/victoria-metrics-auth/README.md
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-gateway/CHANGELOG.md
- charts/victoria-metrics-gateway/Chart.yaml
- charts/victoria-metrics-gateway/README.md
- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/Chart.yaml
- charts/victoria-metrics-operator/README.md
- charts/victoria-metrics-operator/templates/crd_clusterrole.yaml
- charts/victoria-metrics-operator/values.yaml
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/Chart.yaml
- charts/victoria-metrics-single/README.md
follow up:
https://github.com/VictoriaMetrics/helm-charts/pull/995 
https://github.com/VictoriaMetrics/helm-charts/pull/996
https://github.com/VictoriaMetrics/helm-charts/pull/1002
> Make up changelogs

- charts/victoria-metrics-operator/Chart.yaml
- charts/victoria-metrics-operator/README.md
k8s-stack need be released after with new operator chart
> prepare release operator

- charts/victoria-metrics-k8s-stack/Chart.lock
- charts/victoria-metrics-k8s-stack/README.md
Sync deps after https://github.com/VictoriaMetrics/helm-charts/pull/1022
> charts/victoria-metrics-k8s-stack: sync deps

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.yaml
- update changelog
- bump chart version
> charts/victoria-metrics-k8s-stack: release latest changes

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
- charts/victoria-metrics-anomaly/templates/controller.yaml
- charts/victoria-metrics-anomaly/values.yaml
- add support of PVC configuration for models storage
- fix pod security policy being ignored
> charts/anomaly: add ability to use PVC for models storage

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/values.yaml
- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/README.md
- charts/victoria-metrics-operator/templates/uninstall_hook.yaml
- charts/victoria-metrics-operator/values.yaml
> replaced deprecated hyperkube image with bitnami/kubectl

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/templates/server-statefulset.yaml
- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/templates/statefulset.yaml
- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/templates/controller.yaml
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/templates/server-statefulset.yaml
address https://github.com/VictoriaMetrics/helm-charts/issues/1092
> add missing API version and kind for volumeClaimTemplates

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.lock
- charts/victoria-metrics-k8s-stack/Chart.yaml
Make a major release for breaking changes.
> Release k8s stack

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
- charts/victoria-metrics-anomaly/values.yaml
- hack/vmanomaly-lint-hack.yaml
- scheduler and model aliases 
- short class names for models, reader, writer, schedulers
- sampling period in hack
> vmanomaly: changes in v1.13.2 - aliases

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
- charts/victoria-metrics-anomaly/values.yaml
- hack/vmanomaly-lint-hack.yaml
- leave empty schedulers and models section to fix aliases error
- update to 1.13.3 with fixes of Holt-Winters config validation error
> Vmanomaly: config validation error fix

- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
Context: https://github.com/VictoriaMetrics/helm-charts/issues/1181
> Use custom volumeClaimTemplates name for volume name in vmstorage volumeMounts

- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-operator/Chart.yaml
victoria-metrics-k8s-stack needs to be released after operator
> prepare release

- charts/victoria-metrics-agent/values.yaml
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/values.yaml
- charts/victoria-metrics-auth/values.yaml
- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-cluster/values.yaml
- charts/victoria-metrics-single/README.md
- charts/victoria-metrics-single/values.yaml
Hi, 
i did noticed that the link explaining how to use flags through envs vars was not working. 
I did find it in docs so i updated the ReadMe and values.yaml accordingly
regards
> update envs and flags documentation link

- Makefile
- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/files/dashboards/generated/etcd.yaml
- charts/victoria-metrics-k8s-stack/files/rules/generated/etcd.yaml
- charts/victoria-metrics-k8s-stack/files/rules/generated/kubernetes-apps.yaml
- charts/victoria-metrics-k8s-stack/files/rules/generated/kubernetes-resources.yaml
- charts/victoria-metrics-k8s-stack/hack/Dockerfile
- charts/victoria-metrics-k8s-stack/hack/Makefile
- charts/victoria-metrics-k8s-stack/hack/requirements.txt
- charts/victoria-metrics-k8s-stack/hack/sync_grafana_dashboards.py
- charts/victoria-metrics-k8s-stack/hack/sync_rules.py
> support jsonnet import

- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/values.yaml
> victoria-metrics-single: fixed relabeling inconsistencies

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/templates/rules/rule.yaml
> fixed exact rule annotation propagation to other rules

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
- charts/victoria-metrics-anomaly/values.yaml
- hack/helm/victoria-metrics-anomaly/e2e/simple.yaml
- update vmanomaly to 1.15.3
- update configuration examples to match new version
> charts/victoria-metrics-anomaly: update version

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/README.md
- charts/victoria-logs-single/templates/server-deployment.yaml
- charts/victoria-logs-single/templates/server-statefulset.yaml
- charts/victoria-logs-single/values.yaml
- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/README.md
- charts/victoria-metrics-agent/templates/deployment.yaml
- charts/victoria-metrics-agent/templates/statefulset.yaml
- charts/victoria-metrics-agent/values.yaml
- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/templates/alertmanager-deployment.yaml
- charts/victoria-metrics-alert/values.yaml
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-cluster/values.yaml
> added ability to customize emptyDir, which is used either as storage or for caching purposes

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/templates/server-deployment.yaml
- charts/victoria-logs-single/templates/server-statefulset.yaml
- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/templates/deployment.yaml
- charts/victoria-metrics-agent/templates/statefulset.yaml
- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/templates/alertmanager-deployment.yaml
- charts/victoria-metrics-alert/templates/server-deployment.yaml
- charts/victoria-metrics-auth/CHANGELOG.md
- charts/victoria-metrics-auth/templates/deployment.yaml
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/templates/_helpers.tpl
- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-gateway/CHANGELOG.md
- charts/victoria-metrics-gateway/templates/deployment.yaml
- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/templates/deployment.yaml
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/templates/_helpers.tpl
- charts/victoria-metrics-single/templates/server-deployment.yaml
- charts/victoria-metrics-single/templates/server-statefulset.yaml
removed tempating from container names to simplify debugging
> use static container names

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
- charts/victoria-metrics-k8s-stack/values.yaml
- hack/helm/victoria-metrics-k8s-stack/e2e/simple.yaml
> added global license configuration

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/templates/servicemonitors/kubedns.yaml
> fixed kubedns servicemonitor template

- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/README.md
- charts/victoria-metrics-operator/templates/service_scrape.yaml
- charts/victoria-metrics-operator/values.yaml
> added operator service scrape config params to readme

- charts/victoria-logs-single/templates/server-ingress.yaml
- charts/victoria-metrics-agent/templates/ingress.yaml
- charts/victoria-metrics-alert/templates/alertmanager-ingress.yaml
- charts/victoria-metrics-alert/templates/server-ingress.yaml
- charts/victoria-metrics-auth/templates/ingress-internal.yaml
- charts/victoria-metrics-auth/templates/ingress.yaml
- charts/victoria-metrics-cluster/templates/vminsert-ingress.yaml
- charts/victoria-metrics-cluster/templates/vmselect-ingress.yaml
- charts/victoria-metrics-common/templates/_ingress.tpl
- charts/victoria-metrics-gateway/templates/ingress.yaml
- charts/victoria-metrics-single/templates/server-ingress.yaml
- hack/helm/victoria-logs-single/lint/simple.yaml
- hack/helm/victoria-metrics-agent/e2e/simple.yaml
- hack/helm/victoria-metrics-agent/lint/simple.yaml
- hack/helm/victoria-metrics-alert/lint/simple.yaml
- hack/helm/victoria-metrics-auth/e2e/simple.yaml
- hack/helm/victoria-metrics-auth/lint/simple.yaml
- hack/helm/victoria-metrics-cluster/e2e/simple.yaml
- hack/helm/victoria-metrics-cluster/lint/simple.yaml
- hack/helm/victoria-metrics-gateway/e2e/simple.yaml
- hack/helm/victoria-metrics-gateway/lint/simple.yaml
- hack/helm/victoria-metrics-single/lint/simple.yaml
followup for https://github.com/VictoriaMetrics/helm-charts/pull/1257
> support both service port names and numbers in ingress

- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmcluster/ingress-insert.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmcluster/ingress-select.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmcluster/ingress-storage.yaml
followup for https://github.com/VictoriaMetrics/helm-charts/pull/1257
> fixed app label on all ingresses

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/Chart.yaml
- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/Chart.yaml
- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-auth/CHANGELOG.md
- charts/victoria-metrics-auth/Chart.yaml
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-gateway/CHANGELOG.md
- charts/victoria-metrics-gateway/Chart.yaml
- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/ingress.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmagent/ingress.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmalert/ingress.yaml
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/Chart.yaml
victoria-logs-single - 0.6.0
victoria-metrics-agent - 0.11.0
victoria-metrics-alert - 0.10.0
victoria-metrics-auth - 0.5.0
victoria-metrics-cluster - 0.12.0
victoria-metrics-gateway - 0.2.0
victoria-metrics-k8s-stack - 0.25.1
victoria-metrics-single - 0.10.0
> new chart releases

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/templates/server-deployment.yaml
- charts/victoria-logs-single/templates/server-statefulset.yaml
- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/templates/deployment.yaml
- charts/victoria-metrics-agent/templates/statefulset.yaml
- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/templates/alertmanager-deployment.yaml
- charts/victoria-metrics-alert/templates/server-deployment.yaml
- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/templates/controller.yaml
- charts/victoria-metrics-auth/CHANGELOG.md
- charts/victoria-metrics-auth/templates/deployment.yaml
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-gateway/CHANGELOG.md
- charts/victoria-metrics-gateway/templates/deployment.yaml
- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/templates/deployment.yaml
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/templates/server-deployment.yaml
- charts/victoria-metrics-single/templates/server-statefulset.yaml
Fixes https://github.com/VictoriaMetrics/helm-charts/issues/1285
> fixed image pull secrets

- .github/workflows/release.yaml
- Makefile
- charts/victoria-logs-single/Chart.lock
- charts/victoria-metrics-agent/Chart.lock
- charts/victoria-metrics-alert/Chart.lock
- charts/victoria-metrics-anomaly/Chart.lock
- charts/victoria-metrics-auth/Chart.lock
- charts/victoria-metrics-cluster/Chart.lock
- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/Chart.yaml
- charts/victoria-metrics-gateway/Chart.lock
- charts/victoria-metrics-single/Chart.lock
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1287
> publish common chart

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/README.md
- charts/victoria-logs-single/templates/server-deployment.yaml
- charts/victoria-logs-single/templates/server-pvc.yaml
- charts/victoria-logs-single/templates/server-statefulset.yaml
- charts/victoria-logs-single/values.yaml
- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/templates/pvc.yaml
- charts/victoria-metrics-agent/templates/statefulset.yaml
- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/templates/alertmanager-deployment.yaml
- charts/victoria-metrics-alert/templates/alertmanager-pvc.yaml
- charts/victoria-metrics-alert/values.yaml
- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/README.md
- charts/victoria-metrics-anomaly/templates/controller.yaml
- charts/victoria-metrics-anomaly/values.yaml
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-cluster/values.yaml
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/templates/server-deployment.yaml
- charts/victoria-metrics-single/templates/server-pvc.yaml
- charts/victoria-metrics-single/templates/server-statefulset.yaml
Fixes https://github.com/VictoriaMetrics/helm-charts/issues/189
> fixed statefulset pvc mount

- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/Chart.yaml
- charts/victoria-metrics-common/templates/_enterprise.tpl
- charts/victoria-metrics-common/templates/_image.tpl
- charts/victoria-metrics-common/templates/_pod.tpl
- charts/victoria-metrics-operator/Chart.lock
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1296
> moved common templates, fixed case for null in .Values.global

- .github/workflows/run-testing.yaml
- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/README.md
- charts/victoria-metrics-anomaly/templates/NOTES.txt
- charts/victoria-metrics-anomaly/values.yaml
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-cluster/templates/_helpers.tpl
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-cluster/values.yaml
- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/Chart.yaml
- charts/victoria-metrics-common/templates/_enterprise.tpl
- charts/victoria-metrics-common/templates/_image.tpl
- charts/victoria-metrics-common/templates/_pod.tpl
- charts/victoria-metrics-gateway/CHANGELOG.md
- charts/victoria-metrics-gateway/README.md
- charts/victoria-metrics-gateway/templates/deployment.yaml
- charts/victoria-metrics-gateway/values.yaml
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/README.md
- charts/victoria-metrics-single/templates/_helpers.tpl
- charts/victoria-metrics-single/templates/server-deployment.yaml
- charts/victoria-metrics-single/templates/server-statefulset.yaml
- charts/victoria-metrics-single/values.yaml
- hack/helm/victoria-metrics-anomaly/e2e/simple.yaml
- hack/helm/victoria-metrics-anomaly/lint/simple.yaml
- hack/helm/victoria-metrics-gateway/e2e/simple.yaml
- hack/helm/victoria-metrics-gateway/lint/simple.yaml
- remove eula flag support
- updated `vm.args` template structure to embed all args in to a dict, which allows to unmarshal values later
> removed eula support

- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmalert/notifiers.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmcluster/ingress-insert.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmcluster/ingress-select.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmcluster/ingress-storage.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmcluster/vmcluster.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmsingle/ingress.yaml
fixed some bugs
renamed `global` var to `helm` in template context for better readability
replaced `vmService` with `appKey`, `vmSecure` with `appSecure` `vmRoute` with `appRoute`
> k8s-stack: fixed bugs, improved readability

- charts/victoria-metrics-cluster/templates/_helpers.tpl
- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
> fixed vmselect flags rendering

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/templates/rules/additionalVictoriaMetricsRules.yml
- hack/helm/victoria-metrics-k8s-stack/lint/simple.yaml
related https://github.com/VictoriaMetrics/helm-charts/pull/1365#issuecomment-2321192410
> Fixed additional rules

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1378
> fixed external notifiers setting, when alertmanager.enabled is false

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmalert/ingress.yaml
https://github.com/VictoriaMetrics/helm-charts/pull/1365#issuecomment-2322359338
> vmalert ingress name typo

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/ingress.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmagent/ingress.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmalert/ingress.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmsingle/ingress.yaml
related https://github.com/VictoriaMetrics/helm-charts/pull/1365#issuecomment-2322940959
> fixed ingress extraPaths and externalVM urls rendering

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/Chart.yaml
- charts/victoria-logs-single/templates/server-statefulset.yaml
- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-agent/templates/statefulset.yaml
- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
- charts/victoria-metrics-anomaly/templates/controller.yaml
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/Chart.yaml
- charts/victoria-metrics-single/templates/server-statefulset.yaml
related https://github.com/VictoriaMetrics/helm-charts/pull/1297#pullrequestreview-2276092046
> fixed PVC in statefulset

- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-operator/Chart.yaml
need to release operator first
> upgrade operator and decrement k8s stack temporary

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/README.md.gotmpl
- charts/victoria-metrics-k8s-stack/files/dashboards/generated/etcd.yaml
- charts/victoria-metrics-k8s-stack/files/dashboards/generated/grafana-overview.yaml
- charts/victoria-metrics-k8s-stack/files/dashboards/generated/kubernetes-system-coredns.yaml
- charts/victoria-metrics-k8s-stack/files/dashboards/generated/kubernetes-views-global.yaml
- charts/victoria-metrics-k8s-stack/files/dashboards/generated/kubernetes-views-namespaces.yaml
- charts/victoria-metrics-k8s-stack/files/dashboards/generated/kubernetes-views-pods.yaml
- charts/victoria-metrics-k8s-stack/files/dashboards/generated/node-exporter-full.yaml
- charts/victoria-metrics-k8s-stack/files/dashboards/generated/victoriametrics-backupmanager.yaml
- charts/victoria-metrics-k8s-stack/files/dashboards/generated/victoriametrics-cluster.yaml
- charts/victoria-metrics-k8s-stack/files/dashboards/generated/victoriametrics-operator.yaml
- charts/victoria-metrics-k8s-stack/files/dashboards/generated/victoriametrics-single-node.yaml
- charts/victoria-metrics-k8s-stack/files/dashboards/generated/victoriametrics-vmagent.yaml
- charts/victoria-metrics-k8s-stack/files/dashboards/generated/victoriametrics-vmalert.yaml
- charts/victoria-metrics-k8s-stack/hack/sync_dashboards.py
- charts/victoria-metrics-k8s-stack/templates/grafana/dashboard.yaml
- charts/victoria-metrics-k8s-stack/templates/servicemonitors.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1409
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1414
> Added a note about to big dashboards rendering, fixed chart dashboards

- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/templates/clusterrole.yaml
- charts/victoria-metrics-agent/templates/hpa.yaml
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/templates/vminsert-hpa.yaml
- charts/victoria-metrics-cluster/templates/vmselect-hpa.yaml
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/templates/clusterrole.yaml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1438
> removed deprecated api from rbac

- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/templates/_helpers.tpl
- charts/victoria-metrics-alert/templates/alertmanager-configmap.yaml
- charts/victoria-metrics-alert/templates/alertmanager-deployment.yaml
- charts/victoria-metrics-alert/templates/alertmanager-service.yaml
- charts/victoria-metrics-alert/templates/clusterrolebinding.yaml
- charts/victoria-metrics-alert/templates/server-deployment.yaml
- charts/victoria-metrics-alert/templates/serviceaccount.yaml
- charts/victoria-metrics-alert/templates/vpa.yaml
- charts/victoria-metrics-alert/values.yaml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/856
> fixed alertmanager ipv6 compatibility

- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
fixed typo in priority class templating
> cluster: fixed priority class name

- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/templates/_service.tpl
- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1449
> fixed proto, when TLS is enabled

- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-operator/Chart.yaml
> release operator first

- charts/victoria-logs-single/Chart.lock
- charts/victoria-metrics-agent/Chart.lock
- charts/victoria-metrics-alert/Chart.lock
- charts/victoria-metrics-anomaly/Chart.lock
- charts/victoria-metrics-auth/Chart.lock
- charts/victoria-metrics-cluster/Chart.lock
- charts/victoria-metrics-gateway/Chart.lock
- charts/victoria-metrics-k8s-stack/Chart.lock
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-single/Chart.lock
> upgraded deps and bumped k8s-stack chart version

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
- charts/victoria-metrics-anomaly/values.yaml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1476
> vmanomaly: removed not loggerFormat flag from extraArgs

- .github/workflows/release.yaml
- .gitignore
- README.md
- charts/victoria-logs-single/README.md
- charts/victoria-logs-single/README.md.gotmpl
- charts/victoria-metrics-agent/README.md
- charts/victoria-metrics-agent/README.md.gotmpl
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/README.md.gotmpl
- charts/victoria-metrics-anomaly/README.md
- charts/victoria-metrics-anomaly/README.md.gotmpl
- charts/victoria-metrics-auth/README.md
- charts/victoria-metrics-auth/README.md.gotmpl
- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-cluster/README.md.gotmpl
- charts/victoria-metrics-distributed/README.md
- charts/victoria-metrics-distributed/README.md.gotmpl
- charts/victoria-metrics-gateway/Chart.yaml
- charts/victoria-metrics-gateway/README.md
- charts/victoria-metrics-gateway/README.md.gotmpl
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/README.md.gotmpl
- charts/victoria-metrics-operator/README.md
- charts/victoria-metrics-operator/README.md.gotmpl
- charts/victoria-metrics-single/README.md
- charts/victoria-metrics-single/README.md.gotmpl
- added OCI to a doc
- converted OCI repo name to align with repo naming convention
> oci repo to lower case

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/files/dashboards/generated/etcd.yaml
- charts/victoria-metrics-k8s-stack/hack/sync_dashboards.py
renamed repetitive `job` label with `$cluster` value on dashboards to `global.clusterLabel` variable
> fixed ETCD dashboard cluster label

- README.md
- charts/victoria-logs-single/README.md
- charts/victoria-logs-single/README.md.gotmpl
- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/README.md
- charts/victoria-metrics-agent/README.md.gotmpl
- charts/victoria-metrics-agent/templates/_helpers.tpl
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/README.md.gotmpl
- charts/victoria-metrics-anomaly/README.md
- charts/victoria-metrics-anomaly/README.md.gotmpl
- charts/victoria-metrics-auth/README.md
- charts/victoria-metrics-auth/README.md.gotmpl
- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-cluster/README.md.gotmpl
- charts/victoria-metrics-distributed/README.md
- charts/victoria-metrics-distributed/README.md.gotmpl
- charts/victoria-metrics-gateway/README.md
- charts/victoria-metrics-gateway/README.md.gotmpl
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/README.md.gotmpl
- charts/victoria-metrics-operator/README.md
- charts/victoria-metrics-operator/README.md.gotmpl
- charts/victoria-metrics-single/README.md
- charts/victoria-metrics-single/README.md.gotmpl
- hack/docs/template.tmpl
- use common templates for charts documentation
- updated OCI documentation
> updated charts documentation

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmauth/vmauth.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/829
> added vmauth to k8s-stack

- charts/victoria-metrics-k8s-stack/values.minikube.yaml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1541
> k8s-stack: updated minikube values

- REQUIREMENTS.md
- charts/victoria-logs-single/README.md
- charts/victoria-logs-single/README.md.gotmpl
- charts/victoria-metrics-agent/README.md
- charts/victoria-metrics-agent/README.md.gotmpl
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/README.md.gotmpl
- charts/victoria-metrics-anomaly/README.md
- charts/victoria-metrics-anomaly/README.md.gotmpl
- charts/victoria-metrics-auth/README.md
- charts/victoria-metrics-auth/README.md.gotmpl
- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-cluster/README.md.gotmpl
- charts/victoria-metrics-distributed/README.md
- charts/victoria-metrics-distributed/README.md.gotmpl
- charts/victoria-metrics-gateway/README.md
- charts/victoria-metrics-gateway/README.md.gotmpl
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/README.md.gotmpl
- charts/victoria-metrics-k8s-stack/values.minikube.yaml
- charts/victoria-metrics-operator/README.md
- charts/victoria-metrics-operator/README.md.gotmpl
- charts/victoria-metrics-single/README.md
- charts/victoria-metrics-single/README.md.gotmpl
- hack/docs/template.tmpl
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1543
> Updated minikube ETCD default port

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
- charts/victoria-metrics-anomaly/templates/configmap.yaml
- charts/victoria-metrics-anomaly/templates/controller.yaml
- charts/victoria-metrics-anomaly/values.yaml
- hack/helm/victoria-metrics-anomaly/e2e/simple.yaml
- hack/helm/victoria-metrics-anomaly/lint/simple.yaml
- update vmanomaly to 1.16.1
- update configuration for testing to be able to run vmanomaly
- fix configuration templating
- add option to dump models and data
> charts/victoria-metrics-anomaly: update vmanomaly, bugfixes

- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/Chart.yaml
- charts/victoria-metrics-common/templates/_pod.tpl
fixed opsnshift compatibility templates and renamed them
> common: fixed openshift compatibility templates

- charts/victoria-metrics-operator/templates/deployment.yaml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1565
> operator: configurable webhook port on pod

- charts/victoria-metrics-distributed/Chart.lock
- charts/victoria-metrics-k8s-stack/Chart.lock
- charts/victoria-metrics-k8s-stack/Chart.yaml
publishing new k8s-stack release with minor fixes
> k8s-stack: new release

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1587
> fixed default cluster components image tag template

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/files/rules/generated/alertmanager.rules.yaml
- charts/victoria-metrics-k8s-stack/hack/sync_rules.py
disable alertmanager rules alertmanager is disabled
> k8s-stack: updated alertmanager.rules condition

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
Update chart to a [new release of `vmanomaly`](https://docs.victoriametrics.com/anomaly-detection/changelog/#v1170)
> charts/vmanomaly: appVersion 1.17.0

- charts/victoria-metrics-anomaly/CHANGELOG.md
fix old release version  in CHANGELOG.md
> charts/vmanomaly: fix old release version  in CHANGELOG.md

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
> charts/vmanomaly: update app to v1.17.1

- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/templates/serviceaccount.yaml
fixed cluster chart service account annotations
> cluster: fixed service account annotations

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
bump app version to [1.17.2](https://docs.victoriametrics.com/anomaly-detection/changelog/#v1172)
> chart/vmanomaly - appVersion 1.17.2

- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/Chart.yaml
- charts/victoria-metrics-common/templates/_helpers.tpl
added vm.podLabels template, which is used in cluster chart
> common: added vm.podLabels template

- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/templates/_helpers.tpl
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1628
> common: vm.fullname do not add default prefix/suffix, when <component>.fullnameOverride is defined

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmalert/notifiers.yaml
- charts/victoria-metrics-k8s-stack/values.yaml
- fixed default alertmanager rendering while using additionalNotifiersConfig
- added ability to customize vmauth config for vmcluster and externalVM
> k8s-stack: fixed default alertmanager template in additionalNotifiersConfig

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/Chart.yaml
- charts/victoria-logs-single/templates/server-ingress.yaml
- charts/victoria-logs-single/values.yaml
support mulitple paths for each ingress host
> logs: support multiple path for each host in ingress

- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/templates/hpa.yaml
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/templates/hpa.yaml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1641
> support HPA for statefulset

- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/templates/NOTES.txt
- charts/victoria-metrics-operator/templates/_helpers.tpl
- charts/victoria-metrics-operator/templates/cleanup.yaml
- charts/victoria-metrics-operator/templates/crb.yaml
- charts/victoria-metrics-operator/templates/crd.yaml
- charts/victoria-metrics-operator/templates/deployment.yaml
- charts/victoria-metrics-operator/templates/pdb.yaml
- charts/victoria-metrics-operator/templates/rb.yaml
- charts/victoria-metrics-operator/templates/role.yaml
- charts/victoria-metrics-operator/templates/service.yaml
- charts/victoria-metrics-operator/templates/service_account.yaml
- charts/victoria-metrics-operator/templates/service_scrape.yaml
- charts/victoria-metrics-operator/templates/webhook.yaml
migrate operator chart to common templates
> operator: use common templates

- charts/victoria-metrics-alert/templates/_helpers.tpl
- charts/victoria-metrics-alert/templates/alertmanager-configmap.yaml
- charts/victoria-metrics-alert/templates/alertmanager-deployment.yaml
- charts/victoria-metrics-single/templates/relabel-configmap.yaml
- charts/victoria-metrics-single/templates/scrape-configmap.yaml
fixed vmalert flags after refactoring
> vmalert: fixes after refactoring

- charts/victoria-metrics-agent/Chart.yaml
create new vmagent chart release
> vmagent: new release

- charts/victoria-metrics-common/Chart.yaml
- charts/victoria-metrics-common/templates/_helpers.tpl
use app.kubernetes.io/component label with <char.name>-<app> for managed labels
> common: replace app label with component for managed labels

- charts/victoria-logs-single/Chart.lock
- charts/victoria-metrics-agent/Chart.lock
- charts/victoria-metrics-alert/Chart.lock
- charts/victoria-metrics-anomaly/Chart.lock
- charts/victoria-metrics-auth/Chart.lock
- charts/victoria-metrics-cluster/Chart.lock
- charts/victoria-metrics-distributed/Chart.lock
- charts/victoria-metrics-gateway/Chart.lock
- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.lock
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-operator/Chart.lock
- charts/victoria-metrics-single/Chart.lock
updated k8s-stack chart deps, added serviceaccount removal to changelog
> k8s-stack: updated dependencies

- charts/victoria-metrics-agent/templates/clusterrole.yaml
- charts/victoria-metrics-agent/templates/clusterrolebinding.yaml
- charts/victoria-metrics-agent/templates/configmap.yaml
- charts/victoria-metrics-agent/templates/deployment.yaml
- charts/victoria-metrics-agent/templates/hpa.yaml
- charts/victoria-metrics-agent/templates/ingress.yaml
- charts/victoria-metrics-agent/templates/pdb.yaml
- charts/victoria-metrics-agent/templates/pvc.yaml
- charts/victoria-metrics-agent/templates/service-monitor.yaml
- charts/victoria-metrics-agent/templates/service.yaml
- charts/victoria-metrics-agent/templates/serviceaccount.yaml
- charts/victoria-metrics-agent/templates/statefulset.yaml
victoria-metrics-agent chart cleanup
> victoria-metrics-agent: chart cleanup

- charts/victoria-logs-single/templates/NOTES.txt
- charts/victoria-logs-single/templates/_helpers.tpl
- charts/victoria-logs-single/templates/extra-outputs.yaml
- charts/victoria-logs-single/templates/pdb.yaml
- charts/victoria-logs-single/templates/server-deployment.yaml
- charts/victoria-logs-single/templates/server-ingress.yaml
- charts/victoria-logs-single/templates/server-pvc.yaml
- charts/victoria-logs-single/templates/server-service-monitor.yaml
- charts/victoria-logs-single/templates/server-service.yaml
- charts/victoria-logs-single/templates/server-statefulset.yaml
victoria-logs-single chart cleanup
> victoria-logs-single: chart cleanup

- charts/victoria-metrics-single/templates/NOTES.txt
- charts/victoria-metrics-single/templates/_helpers.tpl
- charts/victoria-metrics-single/templates/clusterrole.yaml
- charts/victoria-metrics-single/templates/clusterrolebinding.yaml
- charts/victoria-metrics-single/templates/pdb.yaml
- charts/victoria-metrics-single/templates/relabel-configmap.yaml
- charts/victoria-metrics-single/templates/scrape-configmap.yaml
- charts/victoria-metrics-single/templates/server-deployment.yaml
- charts/victoria-metrics-single/templates/server-ingress.yaml
- charts/victoria-metrics-single/templates/server-pvc.yaml
- charts/victoria-metrics-single/templates/server-service-monitor.yaml
- charts/victoria-metrics-single/templates/server-service.yaml
- charts/victoria-metrics-single/templates/server-statefulset.yaml
- charts/victoria-metrics-single/templates/serviceaccount.yaml
victoria-metrics-single chart cleanup
> victoria-metrics-single: chart cleanup

- charts/victoria-metrics-gateway/templates/_helpers.tpl
- charts/victoria-metrics-gateway/templates/configmap.yaml
- charts/victoria-metrics-gateway/templates/deployment.yaml
- charts/victoria-metrics-gateway/templates/ingress.yaml
- charts/victoria-metrics-gateway/templates/pdb.yaml
- charts/victoria-metrics-gateway/templates/service-monitor.yaml
- charts/victoria-metrics-gateway/templates/service.yaml
- charts/victoria-metrics-gateway/templates/serviceaccount.yaml
victoria-metrics-gateway chart cleanup
> victoria-metrics-gateway: chart cleanup

- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/templates/_helpers.tpl
- charts/victoria-metrics-alert/templates/alertmanager-configmap.yaml
- charts/victoria-metrics-alert/templates/alertmanager-deployment.yaml
- charts/victoria-metrics-alert/templates/alertmanager-ingress.yaml
- charts/victoria-metrics-alert/templates/alertmanager-pvc.yaml
- charts/victoria-metrics-alert/templates/alertmanager-service.yaml
- charts/victoria-metrics-alert/templates/server-alerts-configmap.yaml
- charts/victoria-metrics-alert/templates/server-deployment.yaml
- charts/victoria-metrics-alert/templates/server-ingress.yaml
- charts/victoria-metrics-alert/templates/server-pdb.yaml
- charts/victoria-metrics-alert/templates/server-service.yaml
- charts/victoria-metrics-alert/templates/service-monitor.yaml
- charts/victoria-metrics-alert/templates/serviceaccount.yaml
- charts/victoria-metrics-alert/templates/vpa.yaml
- charts/victoria-metrics-alert/values.yaml
victoria-metrics-alert chart cleanup
> victoria-metrics-alert: chart cleanup

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/templates/_helpers.tpl
- charts/victoria-metrics-anomaly/templates/configmap.yaml
- charts/victoria-metrics-anomaly/templates/controller.yaml
- charts/victoria-metrics-anomaly/templates/pdb.yaml
- charts/victoria-metrics-anomaly/templates/pod-monitor.yaml
vmanomaly: use common templates and chart cleanup
> victoria-metrics-anomaly: use common templates and chart cleanup

- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-cluster/templates/NOTES.txt
- charts/victoria-metrics-cluster/templates/_helpers.tpl
- charts/victoria-metrics-cluster/templates/extra-secrets.yaml
- charts/victoria-metrics-cluster/templates/serviceaccount.yaml
- charts/victoria-metrics-cluster/templates/vmauth-deployment.yaml
- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-cluster/values.yaml
victoria-metrics-cluster  chart cleanup
> victoria-metrics-cluster: chart cleanup

- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/templates/rules/additionalVictoriaMetricsRules.yml
- charts/victoria-metrics-k8s-stack/templates/servicemonitors.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/custom-templates.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/monzo-template.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/vmalertmanager.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmagent/vmagent.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmalert/custom-templates.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmalert/notifiers.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmalert/vmalert.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmauth/vmauth.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmcluster/vmcluster.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmsingle/vmsingle.yml
- hack/helm/victoria-metrics-k8s-stack/e2e/simple.yaml
- hack/helm/victoria-metrics-k8s-stack/lint/simple.yaml
victoria-metrics-k8s-stack chart cleanup
> victoria-metrics-k8s-stack: chart cleanup

- charts/victoria-metrics-operator/templates/_helpers.tpl
- charts/victoria-metrics-operator/templates/cleanup.yaml
- charts/victoria-metrics-operator/templates/crb.yaml
- charts/victoria-metrics-operator/templates/deployment.yaml
- charts/victoria-metrics-operator/templates/pdb.yaml
- charts/victoria-metrics-operator/templates/rb.yaml
- charts/victoria-metrics-operator/templates/role.yaml
- charts/victoria-metrics-operator/templates/service.yaml
- charts/victoria-metrics-operator/templates/service_account.yaml
- charts/victoria-metrics-operator/templates/service_scrape.yaml
- charts/victoria-metrics-operator/templates/webhook.yaml
victoria-metrics-operator chart cleanup
> victoria-metrics-operator: chart cleanup

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/files/dashboards/generated/victorialogs.yaml
- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/files/dashboards/generated/kubernetes-views-namespaces.yaml
- charts/victoria-metrics-k8s-stack/files/dashboards/generated/victoriametrics-cluster.yaml
- charts/victoria-metrics-k8s-stack/files/dashboards/generated/victoriametrics-single-node.yaml
- charts/victoria-metrics-k8s-stack/files/dashboards/generated/victoriametrics-vmagent.yaml
- charts/victoria-metrics-k8s-stack/files/dashboards/generated/victoriametrics-vmalert.yaml
> updated dashboards

- charts/victoria-logs-single/templates/server-deployment.yaml
- charts/victoria-logs-single/templates/server-statefulset.yaml
- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/templates/_helpers.tpl
- charts/victoria-metrics-agent/templates/deployment.yaml
- charts/victoria-metrics-agent/templates/statefulset.yaml
- charts/victoria-metrics-agent/values.yaml
- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/templates/alertmanager-deployment.yaml
- charts/victoria-metrics-alert/templates/server-deployment.yaml
- charts/victoria-metrics-alert/values.yaml
- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/templates/controller.yaml
- charts/victoria-metrics-anomaly/values.yaml
- charts/victoria-metrics-auth/CHANGELOG.md
- charts/victoria-metrics-auth/templates/deployment.yaml
- charts/victoria-metrics-auth/values.yaml
- charts/victoria-metrics-gateway/CHANGELOG.md
- charts/victoria-metrics-gateway/templates/deployment.yaml
- charts/victoria-metrics-gateway/values.yaml
- charts/victoria-metrics-operator/templates/deployment.yaml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1687
> added podLabels to all charts and disabled passing extraLabels for pods

- .github/workflows/release.yaml
- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/Chart.yaml
- charts/victoria-logs-single/templates/extra-outputs.yaml
- charts/victoria-logs-single/values.yaml
- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-auth/Chart.yaml
- charts/victoria-metrics-gateway/Chart.yaml
- charts/victoria-metrics-single/Chart.yaml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1660, https://github.com/VictoriaMetrics/helm-charts/issues/1693
> logs: added json parsing

- charts/victoria-logs-single/Chart.lock
- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/Chart.lock
- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/Chart.lock
- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.lock
- charts/victoria-metrics-auth/CHANGELOG.md
- charts/victoria-metrics-auth/Chart.lock
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/Chart.lock
- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-distributed/CHANGELOG.md
- charts/victoria-metrics-distributed/Chart.lock
- charts/victoria-metrics-gateway/CHANGELOG.md
- charts/victoria-metrics-gateway/Chart.lock
- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.lock
- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/Chart.lock
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/Chart.lock
updated common chart with boolean args fix
> updated common dependency

- charts/victoria-logs-single/values.yaml
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/Chart.yaml
- charts/victoria-metrics-single/templates/_helpers.tpl
- charts/victoria-metrics-single/templates/server-deployment.yaml
- charts/victoria-metrics-single/templates/server-statefulset.yaml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1700
> single: fixed ability to pass a custom scrape config

- .github/workflows/release.yaml
cannot release new charts as wrong path was mistakenly set in actions conditions
> fixed release notes path

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/files/dashboards/generated/etcd.yaml
- hack/rules-and-dashboards/sync_dashboards.py
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1713
> fixed etcd dashboard cluster variable

- charts/victoria-logs-single/README.md
- charts/victoria-logs-single/README.md.gotmpl
- charts/victoria-metrics-k8s-stack/README.md
updated readme for victoria-logs-single chart
> vlogs: updated log agent in readme

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/Chart.lock
- charts/victoria-logs-single/Chart.yaml
- charts/victoria-logs-single/values.yaml
- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/Chart.lock
- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/Chart.lock
- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.lock
- charts/victoria-metrics-auth/CHANGELOG.md
- charts/victoria-metrics-auth/Chart.lock
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/Chart.lock
- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-distributed/CHANGELOG.md
- charts/victoria-metrics-distributed/Chart.lock
- charts/victoria-metrics-gateway/CHANGELOG.md
- charts/victoria-metrics-gateway/Chart.lock
- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.lock
- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/Chart.lock
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/Chart.lock
common chart dependency upgrade should address issue https://github.com/VictoriaMetrics/helm-charts/issues/1716
> updated common chart

- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/README.md
- charts/victoria-metrics-operator/templates/crd.yaml
- charts/victoria-metrics-operator/values.yaml
also reverted removal of option to disable CRD in operator. fixes https://github.com/VictoriaMetrics/helm-charts/issues/1730
> operator: added crds.enabled flag

- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/templates/_helpers.tpl
- charts/victoria-metrics-agent/templates/configmap.yaml
- charts/victoria-metrics-agent/templates/deployment.yaml
- charts/victoria-metrics-agent/templates/statefulset.yaml
- charts/victoria-metrics-agent/values.yaml
- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/templates/_helpers.tpl
- charts/victoria-metrics-alert/templates/alertmanager-configmap.yaml
- charts/victoria-metrics-alert/templates/alertmanager-deployment.yaml
- charts/victoria-metrics-alert/templates/server-alerts-configmap.yaml
- charts/victoria-metrics-alert/templates/server-deployment.yaml
- charts/victoria-metrics-gateway/CHANGELOG.md
- charts/victoria-metrics-gateway/templates/_helpers.tpl
- charts/victoria-metrics-gateway/templates/configmap.yaml
- charts/victoria-metrics-gateway/templates/deployment.yaml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1734
> added configmap template

- charts/victoria-metrics-agent/README.md
- charts/victoria-metrics-agent/values.yaml
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-alert/values.yaml
- charts/victoria-metrics-anomaly/README.md
- charts/victoria-metrics-anomaly/values.yaml
- charts/victoria-metrics-auth/README.md
- charts/victoria-metrics-auth/values.yaml
- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-cluster/values.yaml
- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/Chart.yaml
- charts/victoria-metrics-common/templates/_helpers.tpl
- charts/victoria-metrics-gateway/README.md
- charts/victoria-metrics-gateway/values.yaml
- charts/victoria-metrics-single/README.md
- charts/victoria-metrics-single/values.yaml
use `name` overrideKey for managed resources and `fullnameOverride` for plain ones
removed impact of `name` param on plain resources
clarified fullnameOverride, nameOverride and name params in docs
> common: added overrideKey to support different override keys for plain an managed resources, clarified params in docs

- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/Chart.lock
- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/templates/vmauth-deployment.yaml
- charts/victoria-metrics-cluster/tests/__snapshot__/hpa_test.yaml.snap
- charts/victoria-metrics-cluster/tests/__snapshot__/ingress_test.yaml.snap
- charts/victoria-metrics-cluster/tests/__snapshot__/service_test.yaml.snap
- charts/victoria-metrics-cluster/tests/__snapshot__/vmauth_test.yaml.snap
- charts/victoria-metrics-cluster/tests/__snapshot__/vminsert_test.yaml.snap
- charts/victoria-metrics-cluster/tests/__snapshot__/vmselect_test.yaml.snap
- charts/victoria-metrics-cluster/tests/__snapshot__/vmstorage_test.yaml.snap
- charts/victoria-metrics-cluster/tests/hpa_test.yaml
- charts/victoria-metrics-cluster/tests/ingress_test.yaml
- charts/victoria-metrics-cluster/tests/service_test.yaml
- charts/victoria-metrics-cluster/tests/vmauth_test.yaml
- charts/victoria-metrics-cluster/tests/vminsert_test.yaml
- charts/victoria-metrics-cluster/tests/vmselect_test.yaml
- charts/victoria-metrics-cluster/tests/vmstorage_test.yaml
new release for cluster chart and added unit some tests
> cluster: tests and new release

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
A patch release to fix a bug found in 1.18.1 (and in 1.18.2, as a result)
> charts/vmanomaly - release 1.18.3

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/vmalertmanager.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmagent/vmagent.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmalert/vmalert.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmauth/vmauth.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmcluster/vmcluster.yaml
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmsingle/vmsingle.yml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1778
> k8s-stack: allow CR name override using component.name parameter

- charts/victoria-metrics-auth/CHANGELOG.md
- charts/victoria-metrics-auth/templates/ingress.yaml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1777
> vmauth: fixed multiple ingress rendering

- charts/victoria-logs-single/README.md
- charts/victoria-logs-single/values.yaml
- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/Chart.yaml
- charts/victoria-metrics-common/README.md
- charts/victoria-metrics-common/templates/_helpers.tpl
- charts/victoria-metrics-common/templates/_image.tpl
- test-charts/victoria-metrics-common/tests/helpers_test.yaml
- test-charts/victoria-metrics-common/tests/image_test.yaml
render generated name in `vm.app.name` template
minor refactoring
> common: render template in vm.app.name

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/templates/dashboard.yaml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1795
> vlogs: removed duplicated app label from dashboards

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/vmalertmanager.yaml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1805
> k8s-stack: fixed alertmanager config name

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
charts/vmanomaly - update app to v1.18.6
> charts/vmanomaly - update app to v1.18.6

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
charts/vmanomaly - update app to v.1.18.7
> charts/vmanomaly - update app to v.1.18.7

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/Chart.yaml
- charts/victoria-logs-single/templates/server-service.yaml
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/templates/service.yaml
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/templates/server-service.yaml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1838
> do not set clusterIP for type != ClusterIP

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
charts/vmanomaly - update app to v1.18.8
> charts/vmanomaly - update app to v1.18.8

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.lock
- charts/victoria-metrics-k8s-stack/Chart.yaml
Updated Chart dependencies. Worked fine in my AKS cluster.
> k8s-stack: Dependency chart updates 2024-12-11

- charts/victoria-metrics-alert/values.yaml
> Miss aligned comments

- .github/workflows/release.yaml
- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/Chart.yaml
- charts/victoria-metrics-operator/templates/crd.yaml
compact crd, which is rendered as template in operator chart by default
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1888
> operator: compact crd template

- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/README.md
Finish the auto update for the [latest release](https://github.com/VictoriaMetrics/helm-charts/actions/runs/12687268684/job/35361372478).
> Automatic update CHANGELOGs and READMEs

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/Chart.yaml
- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-alert/CHANGELOG.md
- charts/victoria-metrics-alert/Chart.yaml
- charts/victoria-metrics-auth/CHANGELOG.md
- charts/victoria-metrics-auth/Chart.yaml
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-distributed/CHANGELOG.md
- charts/victoria-metrics-distributed/Chart.yaml
- charts/victoria-metrics-gateway/CHANGELOG.md
- charts/victoria-metrics-gateway/Chart.yaml
- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/Chart.yaml
- update VM components to 1.109.0
- update VL to 1.5.0
> charts: update to latest releases

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
charts/vmanomaly: update appVersion to v1.19.0
> charts/vmanomaly: update appVersion to v1.19.0

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
charts/vmanomaly: update appVersion to v1.19.1
> charts/vmanomaly: update appVersion to v1.19.1

- charts/victoria-metrics-auth/templates/deployment.yaml
- charts/victoria-metrics-auth/values.yaml
- charts/victoria-metrics-cluster/templates/vmauth-deployment.yaml
- charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml
- charts/victoria-metrics-cluster/templates/vmselect-statefulset.yaml
- charts/victoria-metrics-cluster/templates/vmstorage-statefulset.yaml
- charts/victoria-metrics-cluster/values.yaml
> Add ability to specify pod lifecycle

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/README.md
- charts/victoria-logs-single/templates/server-service-monitor.yaml
- charts/victoria-logs-single/values.yaml
> Add-vmServiceScrape-object

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/Chart.yaml
- bump VictoriaLogs to 1.8.0
- update chart version to trigger release
> docs/victoria-logs-single: update VL version, chart version

- charts/victoria-metrics-auth/Chart.yaml
- charts/victoria-metrics-auth/templates/secret.yaml
- charts/victoria-metrics-auth/values.yaml
To be able to use secrets webhook
> Add annotations for config secret

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.lock
- charts/victoria-metrics-k8s-stack/Chart.yaml
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/values.yaml
closes https://github.com/VictoriaMetrics/helm-charts/issues/2042
> k8s-stack: removed prometheus-operator-crds subchart

- charts/victoria-logs-single/CHANGELOG.md
- charts/victoria-logs-single/Chart.yaml
- charts/victoria-logs-single/templates/server.yaml
- charts/victoria-logs-single/tests/__snapshot__/server_test.yaml.snap
- charts/victoria-logs-single/tests/server_test.yaml
- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-agent/templates/server.yaml
- charts/victoria-metrics-cluster/CHANGELOG.md
- charts/victoria-metrics-cluster/Chart.yaml
- charts/victoria-metrics-cluster/templates/vmselect-server.yaml
- charts/victoria-metrics-single/CHANGELOG.md
- charts/victoria-metrics-single/Chart.yaml
- charts/victoria-metrics-single/templates/server.yaml
- charts/victoria-metrics-single/tests/__snapshot__/server_test.yaml.snap
- charts/victoria-metrics-single/tests/server_test.yaml
> properly template existingClaim for statefulSet mode. fixes #2056

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
[Patch release](https://docs.victoriametrics.com/anomaly-detection/changelog/#v1201) update
> charts/vmanomaly - update appVersion to v1.20.1

- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/Chart.yaml
- charts/victoria-metrics-agent/templates/_helpers.tpl
- charts/victoria-metrics-common/CHANGELOG.md
- charts/victoria-metrics-common/Chart.yaml
- charts/victoria-metrics-common/templates/_pod.tpl
insert empty values for absent list flags
> agent: add empty values for absent list cmd flags in remoteWrite.

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
- charts/victoria-metrics-anomaly/templates/controller.yaml
- charts/victoria-metrics-anomaly/values.yaml
- hack/helm/victoria-metrics-anomaly/e2e/simple.yaml
- hack/helm/victoria-metrics-anomaly/lint/simple.yaml
- upgrade anomaly to v1.21.0
- add support of sharding and high availability (replication)
> charts/vmanomaly: add support of sharding

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
- charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmalert/notifiers.yaml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/2075
> k8s-stack: fixed additional notifier config rendering

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
fixes https://github.com/VictoriaMetrics/helm-charts/issues/1994
> k8s-stack: add default vmalert source

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
- charts/victoria-metrics-k8s-stack/values.yaml
add .Values.vmcluster.spec.vmselect.enabled and .Values.vmcluster.spec.vminsert.enabled to disable vmselect and vminsert. fixes #2059
> add ability to disable vmselect and vminsert.

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/templates/_helpers.tpl
- charts/victoria-metrics-k8s-stack/values.yaml
fixes https://github.com/VictoriaMetrics/helm-charts/issues/2092
> override datasource name for external grafana

- charts/victoria-logs-single/Chart.yaml
update VictoriaLogs Helm chart to use v1.18.0
> update Victoria Logs to v1.18.0

- Makefile
- charts/victoria-logs-single/README.md
- charts/victoria-metrics-agent/README.md
- charts/victoria-metrics-alert/README.md
- charts/victoria-metrics-anomaly/README.md
- charts/victoria-metrics-auth/README.md
- charts/victoria-metrics-cluster/README.md
- charts/victoria-metrics-common/README.md
- charts/victoria-metrics-distributed/README.md
- charts/victoria-metrics-gateway/README.md
- charts/victoria-metrics-k8s-stack/README.md
- charts/victoria-metrics-k8s-stack/README.md.gotmpl
- charts/victoria-metrics-k8s-stack/values.yaml
- charts/victoria-metrics-operator-crds/README.md
- charts/victoria-metrics-operator/README.md
- charts/victoria-metrics-single/README.md
- hack/docs/Dockerfile
use paragraph per chart value instead of table to have less visualization issues in docs site and to have links to these values, which can be useful to reference in github issues
> generate paragraph per chart value instead of table

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
- charts/victoria-metrics-anomaly/templates/configmap.yaml
- Update anomaly to 1.24.0
- Automatically enable state restoration feature in case persistence is enabled
> charts/anomaly: update to v1.24.0

- charts/victoria-metrics-anomaly/CHANGELOG.md
- charts/victoria-metrics-anomaly/Chart.yaml
patch release with the bugfixes for 1.23.0+ (1.24.1)
> charts/anomaly: update to v1.24.1

- charts/victoria-metrics-k8s-stack/CHANGELOG.md
- charts/victoria-metrics-k8s-stack/Chart.lock
- charts/victoria-metrics-k8s-stack/Chart.yaml
- update operator
- bump chart version for release
> charts/k8s-stack: update operator to 0.60.1

- charts/victoria-metrics-alert/templates/_helpers.tpl
> fix: don't print server.notifier.alertmanager.url if empty

- charts/victoria-metrics-operator/CHANGELOG.md
- charts/victoria-metrics-operator/templates/cleanup.yaml
Add securityContext to the pod created by the cleanup-hook job
> Add securityContext to cleanup hook

- charts/victoria-metrics-agent/CHANGELOG.md
- charts/victoria-metrics-agent/templates/configmap.yaml
Call tpl function on ConfigMap creation.
Enable the possibility of having ` {{ .Values.myVar }} `inside the object in values.yaml
> vmagent: render helm variables in VMAgent ConfigMap
